### ISSUE TITLE
linux - scroll bar of cell overlaps controls on next cell

### ISSUE THREAD

**Issue by sneha-bharti** [att/rcloud#1026]
In <b>Chrome</b>,
![overlapcellchrome](https://cloud.githubusercontent.com/assets/5227441/4842355/53af21da-6024-11e4-9a9d-b6f3be763893.png)
In <b>Firefox</b>,
![overlapcellfirefox](https://cloud.githubusercontent.com/assets/5227441/4842360/61d0e294-6024-11e4-8b82-0c3f13c01378.png)

**Comment by gordonwoodhull** [comment]
Better now (but not perfect because scroll bar and join button are in same place:

firefox:
![image](https://cloud.githubusercontent.com/assets/1366709/6202661/c7a0b3b0-b4c5-11e4-9d5c-cda0c9b22a50.png)

chrome:
![image](https://cloud.githubusercontent.com/assets/1366709/6202668/179a41a6-b4c6-11e4-884c-659e8a7c4cbf.png)

**Comment by gordonwoodhull** [comment]
Same on Windows, not perfect but ok:

chrome:
![image](https://cloud.githubusercontent.com/assets/1366709/6202681/98270cfa-b4c6-11e4-84c8-f7d1b28aaf35.png)

firefox:
![image](https://cloud.githubusercontent.com/assets/1366709/6202682/aa1f4e0e-b4c6-11e4-8fcb-8bb9032b2424.png)


The layout was changed for many other reasons
