### ISSUE TITLE
could not access rcloud login after the Hadoop is deployed.

### ISSUE THREAD

**Issue by gz5427** [att/rcloud#1189]
Dear rcloud supporters and fellow rcloud users,

I am trying to get the Hadoop to work with the Rcloud1.2 AMI from Amazon EC2.   The Rcloud was set up by default user "Ubuntu". And my Hadoop was set up under the user "Ubuntu" as well.  

The Rcloud was working. But I have some issue to get the Hadoop to work with RCloud. I created a new user called "hduser" at my RCloud instance and at the Hadoop file system as well. And I tried to assign the "hduser" to the group "Ubuntu" so it can access the hadoop logs as well as otherhadoop files.  For some reason, this won't work. Even though "hduser" was a member of "Ubuntu" group, it still could not access the logs directory. Through some research on the internet, I felt like it's better that I set up the hadoop using a dedicated user, not using the "Ubuntu".

The next thing I tried is to change the owner of the whole /data/rcloud directory to be "hduser". And set up the Hadoop file system usin the user "hduser".  The Rcloud works well before I deploy the Hadoop cluster.  For some reason, after the Hadoop cluster was set up, I can no longer log on to the RCloud, and the error message I got is the following:

Error in function (type, msg, asError = TRUE)  : 
  Failed to connect to 127.0.0.1 port 4301: Connection refused

Any help on this would be appreciated!  

Thanks,
Max

**Comment by prateek05** [comment]
Max,
Looks like your session keyserver is down. If your using Amazon image for rcloud you should be able to services rcloud-sks restart or services rcloud-sks stop and then rcloud-sks start. Most likely it happened because you changed the ownership of the sks key.db and the original owner of the sks process cannot read write to it anymore. 

Do drop me an email and I ll help you fix it. Also close this ticket it is not rcloud related mostly hadoop and system administration. 
Thanks,
Prateek

**Comment by mzhao577** [comment]
Hi Prateek,

Please close this ticket.  I have figured it out to have hadoop work
without changing the owner of rcloud.

Thanks,
Max

On Tue, Jan 20, 2015 at 11:42 AM, Prateek Baranwal <notifications@github.com
