### ISSUE TITLE
indicator for cells without results?

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#1207]
Two cases here:

 1. A cell that has not been run.  Currently we show nothing at all - the results div is empty/hidden, since *(no result)* and *(uncomputed)* were both unpopular.
 2. A cell that has been run but returned nothing (invisible/undefined). Currently there is a bug where it shows *Receiving...* (because it hasn't received anything to replace the progress message) but it should show something (or nothing) when the cell completes.

If there is anyone out there, what do you think each of these should show?

**Comment by holyguster** [comment]
Suggestion here...

How about enable/disable with user options.  Maybe something like:

  For (1), "Show whether or not a cell has been computed."
  For (2), "Show when executing a cell completed, but returned no result to display."

Maybe these could both be enabled by default, and users can turn off if they don't like/want it.

Gus

On Jan 27, 2015, at 9:30 PM, "Gordon Woodhull" <notifications@github.com<mailto:notifications@github.com>> wrote:


Two cases here:

 1.  A cell that has not been run. Currently we show nothing at all - the results div is empty/hidden, since (no result) and (uncomputed) were both unpopular.
 2.  A cell that has been run but returned nothing (invisible/undefined). Currently there is a bug where it shows Receiving... (because it hasn't received anything to replace the progress message) but it should show something (or nothing) when the cell completes.

If there is anyone out there, what do you think each of these should show?

**Comment by gordonwoodhull** [comment]
Thanks @holyguster, however I am also wondering what it should look like.

I guess one option would be just to display some text with the state, so we'd have "uncomputed" and "empty result".

IMO it would be even better to have a graphical representation that takes up less space and is less cluttered. I guess the old design did have an advantage in this respect: when it ran it turned into Markdown and that was that.

**Comment by gordonwoodhull** [comment]
For 1.3.1 I am going to deal with this in the same way as #1264 indicate whether a cell is running - for now, a simple one-bit indicator light in the status area that indicates whether the current code has been run.  

In later releases, the status will also encompass waiting, running, cancelled, and perhaps error.  So you can quickly scan down the cells and see how far it got.
