### ISSUE TITLE
line numbers no longer showing until click to edit cell

### ISSUE THREAD

**Issue by holyguster** [att/rcloud#1218]
when initially loading a notebook I own, i cannot see the line numbers for a cell until i click to edit that cell.

also, given that i cannot click to edit cells in notebooks owned by others, in notebooks owned by others, i can no longer see the line numbers at all.

see attached screen grabs; the first is from current production, the other two are from rcloud-5 showing pre-click and post click.  same behavior for R and Markdown cells.

could be related to implementation of https://github.com/att/rcloud/issues/1126

![shot1](https://cloud.githubusercontent.com/assets/927657/5948403/9260590a-a712-11e4-97d3-a380d44bfc4e.png)
![shot2](https://cloud.githubusercontent.com/assets/927657/5948404/942538fa-a712-11e4-9ff9-ff90b7647020.png)
![shot3](https://cloud.githubusercontent.com/assets/927657/5948409/96dd4696-a712-11e4-8cd8-d7e18374b4f9.png)

**Comment by gordonwoodhull** [comment]
That's a good point. I kind of regarded it as clutter which was just as good gone, but people might be relying on it.

**Comment by holyguster** [comment]
Right, https://github.com/att/rcloud/issues/1126 specifically mentions referring to both the cell and line numbers when looking to draw attention to specific parts of a notebook.  I believe both cell and line numbers are both important when looking at my own or others notebooks, even if including them is high on the clutter quotient.

**Comment by gordonwoodhull** [comment]
Sounds reasonable. I will see how hard it is. 

Keep in mind that when inactive, these are not the ace widgets but a static rendering of the same material. So it is not exact: the lines may wrap slightly differently,  for example. 

I figured it was better to be close and efficient, rather than exact and slow. We will just have to refine it over time. 

But it should not be hard to duplicate the style for line numbers in the gutter.
