### ISSUE TITLE
cell_view.js hide_buttons and show_buttons on view.html

### ISSUE THREAD

**Issue by cscheid** [att/rcloud#1254]
[These functions cannot possibly work](https://github.com/att/rcloud/blob/develop/htdocs/js/notebook/cell_view.js#L399-L406) in view.html

This seems to have been added by 33050d8bd372b838f17fd6938b38d553054e6bdf, but as it stands, this is referencing a variable that's never initialized when in view mode, as per lines 63--76 of the same file. I'm guessing the jquery variable assignments need to be made regardless of mode, yeah?

**Comment by gordonwoodhull** [comment]
Thanks @cscheid, good eye.

These functions are dead code - there is no need to hide the buttons in view mode, because they are never created. One of the benefits of modularizing the buttons into [cell_commands.js](https://github.com/att/rcloud/blob/develop/htdocs/js/ui/cell_commands.js) is that it became easier to separate functionality.
