### ISSUE TITLE
should cells be colored when not active?

### ISSUE THREAD

**Issue by holyguster** [att/rcloud#1322]
IMHO it was nice that code cells and markdown cells had different background colors without needing to hover over them, as it visually broke up mixed notebooks.  Also, even in motebooks the had only one cell type, the background color helped you easily see cell boundaries vs. the different color background of cell dividers and left gutter.

Was the background color visibility changed to hover-only based on some user feedback or user request?  I did not find a related issue (maybe I am searching for the wrong terms).

**Comment by gordonwoodhull** [comment]
Well, the cells are not active / in edit mode until they are clicked on, and I feel it's more consistent and less busy interface to just have grey code cells until they are clicked on. Think of it as a static page which indicates parts of it are editable by the highlighting on hover.

The feedback that I'm working off was that the old interface was too "heavy", when people complained about too many cells being created, they were annoyed not just by the performance, where a notebook would get slow at 100 cells, but also annoyed that there was so much active user interface "stuff" being created.

So the move here is toward clean lines, less distracting busy-ness outside the code, more like a command line where you happen to be able to go back and change old entries. 

We want to focus on the code and not the UI. The cell commands will also fade, in time.

Thanks for asking, because this is something I just worked on without discussing much here on github. I had an illuminating conversation with @martymcwizard's group and finally understood what they meant by wanting a command line prompt.

**Comment by gordonwoodhull** [comment]
You do have a good point about distinguishing cell types and cell boundaries. This will continue to evolve, so let's talk about how to improve it.

**Comment by gordonwoodhull** [comment]
Tried it out with the less saturated colors used for the hover, liked it, going with it.

Thanks @holyguster!
