### ISSUE TITLE
Command prompt is appearing between two cells after joining the cells

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1352]
Testing on branch 'release/1.3.1'
User has two cells. Each cell produces its own plot after running the programs.

![two cells](https://cloud.githubusercontent.com/assets/9251570/6264137/a35ea67c-b846-11e4-8c79-636418908c79.PNG)

after output is displayed,join the two cells and 'Command prompt' is displaying in between

![command_prompt](https://cloud.githubusercontent.com/assets/9251570/6264216/981efa22-b847-11e4-970f-63ddc28676a0.PNG)

**Comment by sanketd11** [comment]
This may be due to #1354

**Comment by gordonwoodhull** [comment]
This looks like #1048.  I am not able to reproduce either one.  Operating system and browser, please?

**Comment by gordonwoodhull** [comment]
We aren't doing anything interesting with the layout here, there are just a bunch of divs in a row. So I suspect a browser bug. I don't think Ace could be responsible because the div that is out of place is a couple of levels up from there.

Maybe sometime I could remote into a machine that is exhibiting these 3 issues, to see if I can track it down in the debugger?  Because I am stuck if I can't repro.
