### ISSUE TITLE
Record IP address of 'nobody' users

### ISSUE THREAD

**Issue by martymcwizard** [att/rcloud#1416]
Please record/log the IP address of a user who accesses a notebook as 'nobody' in order to capture usage statistics by unique user of applications created in RCloud.

@s-u

**Comment by s-u** [comment]
I'm not sure I understand this request. The IP landing at RCloud is typically not useful since it will be the IP of the proxy - logging of the actual user IP address should be done by the proxy since it is the only place that actually knows the external IP address of the user. Alternatively, we could define a way by which the proxy can relay that information to RCloud (e.g. a HTTP header), but that require cooperation of the proxy and RCloud.

So I'll interpret this as "record a defined header in HTTP requests to ulog".

**Comment by prateek05** [comment]
@s-u We are forwarding the user's real IP using the proxy_set_header directive in the proxy. 
It's just not available in the ulogs. 
<code> proxy_set_header   X-Real-IP  $remote_addr; </code>

**Comment by s-u** [comment]
Added to the WS proxy:
https://github.com/s-u/Rserve/commit/2db1c39f1e9a52d2b92a73cd4a3b982f410a53fa
