### ISSUE TITLE
login redirect does not go to notebook in URL

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#1419]
When you browse to an rcloud URL and you are not logged in, after you log in you land at the last notebook, not the notebook in the URL.

**Comment by gordonwoodhull** [comment]
There are other cases where we don't redirect correctly, but this is the most annoying. One ends  up having to re-click the link after logging in again.

**Comment by gordonwoodhull** [comment]
PR #1077 solved a similar problem, I think not in quite the correct way

https://github.com/att/rcloud/blob/548229e3fadbd4899260a8795432ae007f0d0bd4/htdocs/login.R#L49-L57

If I am not mistaken, the `redirect` query parameter should have all the info we need, and it's not necessary for login.R to support notebook and version parameters.

**Comment by gordonwoodhull** [comment]
This problem is only on the internal deployment - maybe it has something to do with rcloud.html?

**Comment by prateek05** [comment]
Yes. I was discussing this with @s-u the other day. The login page does not post the notebook id parameter back to login.R along with the creds. 

The current redirect also does not account for the interface initially requested. Like if I don't have a valid exec token and clicked view.html shared to me on email. while the routing from view -> login.R the requested interface 'view' is also lost only the nbid is passed through to the login page. 

Sorry just thinking aloud! I am not really sure if passing these as url parameters would be ideal maybe make use of browser local storage. Since there are multiple redirects involved. view > login.R > login Page > github > login_successful > (should go back to view)

**Comment by gordonwoodhull** [comment]
Yes, the view mode versus edit mode on reconnect is #1282, which we also want to fix for 1.4. 

I think using query parameters in the URL should be sufficient. It's a quality of the URL from the originating (logged out) page so it makes sense to keep it there. We already have to keep track of the notebook id and version/tag through all the redirects, and since it works through public GitHub for that one case, it shouldn't be hard to get it working for all cases. Unless I'm missing something.
