### ISSUE TITLE
Enhancement: Imported notebooks should be highlighted in 'Notebooks Div'

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1431]
When we import any notebook using 'Import External Notebook' or 'Import Notebook from File', it gets imported but currently to verify whether it's imported, user needs to look into "Notebooks div" and search for the notebook name. This might be tedious task if there are too many notebooks.
It would be more convenient for users to locate the imported notebook if it gets highlighted in 'Notebooks div' for some time after getting imported.

**Comment by gordonwoodhull** [comment]
this would be nice

**Comment by gordonwoodhull** [comment]
prereq for #1804

**Comment by gordonwoodhull** [comment]
@shaneporter, this has been bothering me recently. 

Any ideas? We want to highlight the newly created notebook (and open the tree to it), however, we don't want to open it. I don't know if the highlight should be temporary (another color then fading to black over say 30s) or permanent.

**Comment by shaneporter** [comment]
@sanketd11 said:

> to verify whether it's imported, user needs to look into "Notebooks div" and search for the notebook name

Is there not an error if the import fails?

Anyway, beyond that, here are my thoughts:

- we don't currently open the notebook (fair enough) because this is about 'importing'. There's no assumption that the user wishes to open it.
- highlighting will make it _easier_ to verify that the notebook has been imported, but for successive imports, do we highlight more than one notebook? When should this highlight be removed? 

So - my suggestion is to log the import as successful (perhaps in the session pane? is that an applicable use case for the session pane?) and provide a link that will open that imported notebook. That way, the import is logged as successful (or otherwise), the user _can_ open it easily (without a search), and it doesn't complicate the notebook tree's UI.

**Comment by gordonwoodhull** [comment]
Yeah, there's an error in the session pane if it fails. But there's no confirmation that it did work. And this isn't really about verification, but the sense that the notebook tree is reacting to the action. 

Already now, if you happen to have that part of the tree open, you'll see it change, and that's pretty helpful.

I don't like the idea of logging it in the session pane or adding links there. That's kind of out of the way and is used more for notebook output and errors.

I think it should scroll to them, open any trees and highlight the new notebooks just for a few seconds. This could just be a jQuery UI highlight like we do for the Run button. If you import a bunch of notebooks and they land all over the place in the tree, causing a lot of scrolling, that's okay. It will settle down. It's also okay that this may cause the notebook tree to scroll somewhere the current notebook is not visible.

If you've got PTSD from dealing with the notebook tree code in the past, I can take this. But I don't think it should be tricky - it doesn't affect the data and shouldn't have any side effects I can think of it. Yes, it's a complicated interface, but it's also a rich one.

**Comment by shaneporter** [comment]
Haha - no I don't have PTSD about the notebook tree code. Happy to take this one.

**Comment by shaneporter** [comment]
To summarise then, when importing a notebook:

1. Scroll to imported notebook's position in the tree. Expand trees where necessary.
2. Highlight element in the tree for a second or two.

It is not important to scroll back to the current notebook.

**Comment by gordonwoodhull** [comment]
Sounds good!
