### ISSUE TITLE
Support group-visible notebooks

### ISSUE THREAD

**Issue by s-u** [att/rcloud#1444]
Allow notebooks to be only visible by a group

- [x] UI for creating a group, the user becomes group-admin
- [x] UI for adding/removing users at/from a group by the group admin
- [x] create group key management infrastructure
- [x] flag own notebook as one of: public, group-only (group-encrypted), private (private encrypted)
- [x] forking a group-only notebook retains the attribute

To contemplate:

- When a person is deleted from the group - what does it mean for his/her group-only notebooks? They become unreadable since the person can no longer obtain the key.
- What happens when a group is deleted? The admin cannot change other's notebooks so they cannot be automatically decrypted.

**Comment by gordonwoodhull** [comment]
@s-u, passing this off to you. The GUI is ready (although I'm sure there are still edge cases). The management of groups is done, although they are just IDs and names, with no encryption keys.

We decided to remove the delete-group button for now because it's extremely dangerous. I can think of a few ways to make this safe and not let get the keys lost permanently, all of which are some work: 
 - Keep the groups but give them some sort of invisible name.
 - Look for notebooks that are in the group, don't allow deleting the group if any notebooks are in it. This is not 100% safe because notebooks are not always registered in RCS.
 - Look for notebooks in the group, if they all belong to the current user, force the user to move them to a different group. Lots of work.

@anatoliyg needs to add the private-encrypted option.

**Comment by s-u** [comment]
Some notes:
* the encryption is entirely transparent - as long as you don't use the raw version of a notebook it has the decrypted content and update requests act as if the notebook was decrypted. The only special case on the update end is the presence of the special encrypted filename which essentially triggers a pass-through.
* SKS doesn't allow a user to remove himself from the admin list. This is to prevent loss of the key. For the same reason you cannot delete a group.
* Details on the design etc are in the Wiki at https://github.com/att/rcloud/wiki/PrivateNotebooks

**Comment by s-u** [comment]
Note: forking should work, but because self-forking on github-backends is not done on the back-end the front-end has to be fixed to relay the cryptogroup information.

**Comment by gordonwoodhull** [comment]
How does the cryptgroup get set when a notebook is forked? Or do you mean the crypto part should work, but the metadata might be wrong in RCS?

**Comment by s-u** [comment]
What I mean is that the back-end takes care of all needed for forking done in the back-end, but the UI doesn't use "fork" for forking your own notebooks on GitHub, so the back-end doesn't know that a fork happened, so the UI has to set the RCS. I'm not sure I know the code the UI uses for that "manual" forking so I don't know if it does a raw copy (in which case it is forked encrypted) or a get+create in which case the copy would be in the clear.

Ideally, we should use the back-end for that case, too, because it has already the implementation of get+create for cross-source forking, but I'm not sure how involved that would be.

**Comment by gordonwoodhull** [comment]
Yes, I understand all of that and agree it would be better to use the back end... if we weren't once again days before the release with dozens of other bugs to think about. 

Notebooks are forked from the GitHub-raw gist because that's how I could get binary assets to work, so that part should work too.

But my question was mostly unrelated. Currently we track what group a notebook is in, not just in the notebook's metadata, but in RCS, with the `cryptgroup` key. And since there is no custom code for forking encrypted notebooks, I don't see how that key could be copied right now. The crypto may work but the UI won't know the group of any notebook without the RCS part.

Sorry, I see I was very unclear!

**Comment by s-u** [comment]
Yes, that's why the UI has to set the RCS setting in accordance to the source notebook (which is knows the groupid for for mits RCS) when it's doing the fake fork (i.e, using `rcloud.set.notebook.cryptgroup` ideally with `modify=FALSE`).

**Comment by s-u** [comment]
Or am I missing something? The back-end fork is setting the RCS key accordingly using the above API.

**Comment by gordonwoodhull** [comment]
Got it. I was just being dense and looking at the wrong commit. Sorry for the noise.

**Comment by gordonwoodhull** [comment]
there are plenty of minor issues to be fixed, but the feature basically works.

congrats @anatoliyg, @s-u, good teamwork on this one!

**Comment by anatoliyg** [comment]
yay!!
