### ISSUE TITLE
Error, after disabling the rcloud.viewer

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1468]
Error is displayed in session div,
1.Disable the rcloud.viewer from the settings
2.Execute a program which generates 'Datafarme'
3.Now click on the 'Dataframe' link, from the Workspace div.
the following error is displayed
![disable_rcloud viewer_click_on_dataframe](https://cloud.githubusercontent.com/assets/10941328/7912367/5f2db180-0884-11e5-9c1f-9bd79ef9d60b.PNG)

**Comment by s-u** [comment]
I don't think we can disable some fundamental pieces of RCloud. The only alternative I could think of for disabled viewer would be to open an editor, but I don't even think we have a provision for that ...

**Comment by gordonwoodhull** [comment]
You have to manually type rcloud.viewer into the Disable Extensions settings in order to trigger this error, so it's really PEBKAC.

The error is actually pretty clear, too. Although it hints that we might not be customizing the data viewer in the best way in rcloud.viewer - right now we actually override `View`, because I did what RStudio does. :stuck_out_tongue_winking_eye:
