### ISSUE TITLE
error forking a notebook with binary assets

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1470]
This issue observed in RCloud-local instance
(commit: 62c60cdc5ab586e932bf4865ba5e89afaea8f658).
When we upload any pdf/png files to the notebook and fork that particular notebook, the following error is displayed in session div.

![upload_pdf_or_png_and_fork](https://cloud.githubusercontent.com/assets/10941328/7980774/d48f342c-0ac7-11e5-9d60-bed9a74986f8.PNG)

**Comment by gordonwoodhull** [comment]
Have you rebuilt and restarted the server? Looks like it could be a mismatch.

**Comment by gordonwoodhull** [comment]
Oh, nevermind, I missed the fork part.

**Comment by gordonwoodhull** [comment]
In #1475, @s-u wrote:
> BTW: we may want to fix rcloud.create.notebook anyway since it should be capable of using the filtering just as rcloud.update.notebook does so that may be the actual bug here regardless of the format we choose ... 
> Yes, that's the bug I meant - rcloud.create.notebook fails to call .gist.binary.process.outgoing() and passes the raw object directly to the gist API which is invalid.

which are really about this issue, which was caused by trying to send raw binary data to `rcloud.create.notebook`

**Comment by gordonwoodhull** [comment]
Which are good points, but it didn't work for me. I tried (just as a test, don't worry):

```
rcloud.create.notebook <- function(content, is.current = TRUE) {
    content <- .gist.binary.process.outgoing("foo", content)
   ...
```
The intentional bad id is to make the `rcloud.get.notebook` fail inside `.gist.binary.process.outgoing`, so that we aren't checking any past content (there is none).

The result was that I got a binary asset back but it was corrupted somehow, entirely different data (?!)

So I settled for forking the github-raw content, since we are fetching the notebook anyway in the self-fork case.
