### ISSUE TITLE
foreign notebooks: populate comments: Unexpected end of input

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#1533]
for some reason, front end is unable to load comments, gets an empty array instead of a JSON string, and barfs.

we can't support writing comments, but maybe we can support reading comments, from other instances. if we care.

**Comment by gordonwoodhull** [comment]
@s-u, any other places we need to check the notebook source and fetch the context? 

### Maybe, eventually every single place we have a notebook id?

**Comment by gordonwoodhull** [comment]
Sorry, this is spinning out of control. Passing this back.

**Comment by s-u** [comment]
Hmm.. essentially whatever we use the gist API for. The hope was that for read-only notebooks this set is limited since there should only be very few read entry points ...

**Comment by gordonwoodhull** [comment]
Sounds like the entire gist API needs to be wrapped again, to me. I give up!

**Comment by s-u** [comment]
Well, the underlying bug here is that `rcloud.get.comments()` is defined to return `list()` on error, so the UI should be able to deal with that (not that I think that's good API - it should really return an error object so the UI can do something more useful with it...)

The secondary bug is that `notebook.comments.R` has not been converted to the .`.rcloud.get.gist.context()` API - somehow it escaped me when I was doing the substitution ... - will fix that.
