### ISSUE TITLE
notebook tree title doesn't update when changing title of encrypted notebook

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#1535]
oddly, the navbar title does update.

too tired to think how this is possible. @s-u, anything different about the update "message" here?

**Comment by gordonwoodhull** [comment]
ah, the title change just doesn't "take" at all.

**Comment by s-u** [comment]
Ah, is it possible that title changes use `rcloud.update.notebook`? If so, can the update contain both metadata and files update? I was expecting update to only affect content since we have to "simulate" what GitHub does for content updates (since we always only update one single file). I guess the non-content updates have to be retained in the update payload...

**Comment by gordonwoodhull** [comment]
Okay, yeah, that probably explains it. Yes, `description` is the one and only item of user-settable metadata.

**Comment by s-u** [comment]
Ok, thanks, should be easy to fix (will see if the plane has WiFi ;))
