### ISSUE TITLE
Incorrect count for search results

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1560]
When any keyword is searched keeping all lakes option selected, the count for search results displayed is incorrect as seen in screenshot below. It seems the search results from other lakes ain't getting considered in count.

![search count](https://cloud.githubusercontent.com/assets/9251570/8349047/914babfc-1ae7-11e5-8d85-a1da1be7b4f7.PNG)

**Comment by gordonwoodhull** [comment]
Thanks @sanketd11. 

Hmm, I thought this was going to be handled by the aggregation before it got to the client.

**Comment by gordonwoodhull** [comment]
This also breaks paging.

**Comment by gordonwoodhull** [comment]
Wow, this is really screwed up, I'm getting 12 results or 166 depending on the sort order.

Told you we shouldn't touch the search code! @s-u, do you have any ideas here, or am I left holding the bag?

**Comment by s-u** [comment]
On the R side the result is simply concatenation of the generated JSON objects. The problem here seems to be that every single object has the `numFound` property which will reflect only the lake the query comes from so the UI must be simply picking one. Is it picking the first one? If so, that could be fixed by re-writing the first row with the sum of all lakes.

**Comment by gordonwoodhull** [comment]
I'm not sure. The 12 vs 166 I mentioned is the size of the array, not the `numFound`.

**Comment by gordonwoodhull** [comment]
It looks like paging is handled on the server side, but we are just concatenating two unrelated pages. The concatenation would have to happen before paging for paging to work.

**Comment by s-u** [comment]
Um, I don't  follow - the screenshot shows more than 5 results but says "5 results" so I would expect that the array has to have more then 5 elements, otherwise it would not show the other results ... AFAICS the reported number *has* to be `numFound` since the array will only have the one page.

Regardless of the reported size, I think I see a much deeper issue - contrary to previous claims the pagination is done at the query level. So I would assign it to Prateek since it was his claim ;). But, seriously, I don't have a solution for this other than separating the pagination for each lake or retrieving all results - and even that would require that SOLR returns some kind of weight you can combine across instances.

**Comment by gordonwoodhull** [comment]
Right, that's my conclusion as well.

Well, here's what I'm going to do so at least we show all the results: take the max of the `numFound`. Then we'll page all of the results in parallel, and we'll get `nLakes * 10` results per page. And show `sum(numFound)` for the number.

**Comment by s-u** [comment]
Sounds good to me ...

**Comment by gordonwoodhull** [comment]
Crap, this means parsing the JSON on the server side. I am dropping this to work on the parts that are my responsibility.

**Comment by gordonwoodhull** [comment]
Another possible solution is to search on one lake at a time: have a dropdown to select the lake, instead of attempting to search all lakes and aggregating them.

However, I have my own bugs to deal with, so I'm still not taking this up.

**Comment by gordonwoodhull** [comment]
@anatoliyg will take on the lake selector, and I'll patch the R source to support this.

**Comment by s-u** [comment]
Sorry, I'm losing you again. What you suggested (paging all lakes at once) is purely JS side - it doesn't involve the server - the UI simply asks for a page at a time based on the max as you described...

That said, searching a lake at a time is trivial on the server side (simply set "source") so anything is fine with me.

**Comment by gordonwoodhull** [comment]
Determining the max and total on the client is complicated (since the results are already concatenated into an array). It would be better to do this on the server when getting the individual results from the different lakes, but that would mean parsing the JSON. 

I'm not picking this up.

**Comment by gordonwoodhull** [comment]
Thanks @s-u, this works!

To summarize: this is a hack to page all lakes "in parallel": the pages from each lake are concatenated. So, for example, if one lake has three results, and the second lake has 17 results, the first page will have 13 results, and the second page will have 7. This is definitely weird behavior but it's the best we could think of given the way search pagination works.
