### ISSUE TITLE
Feature Request: Different colour for indicating original admin's username

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1568]
According to current scenario, If any user creates a group his name will be reflected in admins field automatically also he can add several other users as admin. Now if any other admin user accidentally removes the original admin then he will loose access to all the notebooks in the group including his own notebooks. So to notify other admins about the original/actual owner of group, different color can be used for his username in admins field. This will stop any unintentional removal of original admin from group.

**Comment by s-u** [comment]
There is no such thing as the "original/actual owner". Groups are not owned by anyone, they only have admins that are all equal.

**Comment by gordonwoodhull** [comment]
I agree. The multiple admins feature exists mostly to be able to pass control of a set of notebooks to another user. 

We should improve the error message when failing to open a notebook so that the owner of the notebook knows what group they've been booted out of, and perhaps which admins they can appeal to, to regain access.
