### ISSUE TITLE
forward: rscript.c ignores error code component

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#1594]
This causes parsing errors instead of hard errors when trying to load JS resources from R packages, because e.g. requireJS tries to parse the error message.

**Comment by gordonwoodhull** [comment]
Example: https://rcloud-5.research.att.com/shared.R/shiny/shared/selectize/js/selectize.min.js

(why this was being loaded is another issue)

**Comment by gordonwoodhull** [comment]
@s-u, this appears to be a proxy bug; at least, it appears on rcloud-5, but not rcloud or rcloud-2. 

shared.R returns **404** as expected.

**Comment by s-u** [comment]
Yes, `rscript.c` doesn't parse the error code at all - thus is it simply ignored.

**Comment by s-u** [comment]
There are two different issue here, in fact. 

 - error code in the result is ignored (now fixed by s-u/Rserve@a659766)
 - bogus requests to `shared.R` (like the example above) issue an R-side error which gives a 500 error code, but the actual R-side error is not passed out. This is one a bug per se since the response is correctly an error, but it would be nice to pass the error string through (will do shortly)

**Comment by gordonwoodhull** [comment]
For completeness (and testing), the urls that prompted this were more like

https://rcloud-5.research.att.com/shared.R/shiny/blahblah.js
(package exists but file doesn't)

https://rcloud-5.research.att.com/shared.R/blahblah/foo.js

(package doesn't exist)
