### ISSUE TITLE
in edit.html, run a Markdown or RMarkdown cell in another's notebook, can't get back to source

### ISSUE THREAD

**Issue by holyguster** [att/rcloud#1607]
Looks like I have to reload the page to get back to the Markdown/RMarkdown source when looking at other's notebooks in edit.html.

When looking at my own notebook, I can toggle the source, but when looking at another's notebook, toggle source button is not active, so no way to get back to looking at the Markdown/RMarkdown source without reloading the page.

Seems that there should be a way to get back to looking at the source without reloading.  Maybe toggle source could be active, but not go into edit mode unless I own the notebook?

**Comment by gordonwoodhull** [comment]
That sounds reasonable. Thanks Gus!

**Comment by gordonwoodhull** [comment]
For this point release, you can click on any code within the markdown output in order to get the code to show again. (This is similar to how you can click on the code in order to *edit* it, when the notebook is writeable.)

I won't explain why it's difficult to enable the button. Let's just say that there are some abstractions I put in which are either really brilliant or really stupid.

**Comment by gordonwoodhull** [comment]
My stupid hack caused #1672 and #1681. There ought to be a way to get the button to work!

**Comment by gordonwoodhull** [comment]
Alright, I changed the behavior so that the Edit button controls whether source is shown or not when in readonly mode, and (shows the source if hidden and) toggles edit mode when not readonly as before.

Feels somewhat more consistent now, although it's complicated and please let me know if the new behavior has problems or is confusing.
