### ISSUE TITLE
unable to activate selectize admins/members after deleting item

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1610]
Steps to replicate:
1. Open manage groups
2. Create a new group by adding members
3. Now remove the admin/member, and try to add again
user is not able to add any names unless he needs to click on prompt box and then on admin/members field to add names

**Comment by gordonwoodhull** [comment]
Thanks @Prateek032. To clarify: after deleting a member, the selectize becomes unresponsive to clicking. One has to click on something else and then click back in order to activate it. As a guess, this is probably due to 2b7016c01e724b394fc0900df05f81f5606cefbf, because the dropdown appears for an instant and then disappears.

**Comment by anatoliyg** [comment]
@gordonwoodhull Yea, I was trying to make it so the drop down goes away  because it covers the area of warnings , but that takes the focus out of selectize as well
