### ISSUE TITLE
notebooks with binary content cannot be converted to encrypted

### ISSUE THREAD

**Issue by s-u** [att/rcloud#1616]
There appears to be a bug in GHE that makes it impossible to encrypt notebooks that contain large binary content. To replicate, upload large content to a public (unencrypted) notebook (e.g. 400kB file) and then attempt to convert it to encrypted. Resulting GH request error:

```
gist update error in rcloud.update.notebook on behalf of rcloud.set.notebook.cryptgroup: 
validation failed, gist, missing_field, files, 
https://developer.github.com/enterprise/2.2/v3/gists/#edit-a-gist
```
Note that the error claims that `files` is missing from the request, but that is not true:

    {"files":{"part1.R":null,"part2.R":null,"scratch.R":null,
                 "encrypted.notebook.content.bin.b64":{"content":"## sha1:03b..."}}}

so apparently GHE truncates the request when parsing it, resulting in an error on its end.

Note that if a notebook is private already GHE will correctly update it when large assets are added, so this only affects wholesale conversion that involves removal and insertion.

**Comment by s-u** [comment]
Since there is not much we can do, should we simply disallow conversion of large notebooks for now?

**Comment by gordonwoodhull** [comment]
I haven't tested this yet - will want to know how big is too big and whether this is an issue on public GH as well as GHE. Then, yes, probably. I'll take that.

**Comment by gordonwoodhull** [comment]
I wonder if this was a kink in the truncation fix, or another issue that has gotten resolved. 

I just disabled the asset size limit (#1701) on rcloud-5, uploaded [Moby Dick](http://www.textfiles.com/etext/FICTION/mobydick.txt) (1.2MB), encrypted the notebook, renamed the asset, and unencrypted the notebook with no problems. Same result on my local instance (against public github), although I did get one harmless disconnection error (like #1680).

@sanketd11, @Prateek032, you said you can still repro this? 

I'm leaving the size limit disabled on rcloud-5 for further testing, but don't intend to put that into this release because of the strain that would put on testing.

**Comment by gordonwoodhull** [comment]
Duh. BINARY. Yes, I can reproduce this. I wonder if it has something to do with line lengths, then, since GitHub should not be seeing the binary.

**Comment by gordonwoodhull** [comment]
I can reproduce this with tiny binary asset on either GHE or public github. Passing back to @s-u as I suspect it is just invalid filenames or something.

**Comment by gordonwoodhull** [comment]
Also happens if the binary asset is the only file in the gist (no cells, no other assets).

**Comment by s-u** [comment]
The issue is that it attempts to delete `foo` instead `foo.b64` when binary assets are involved since the content is based on the decoded (and not the raw) form of the gist.
