### ISSUE TITLE
Weird message after clicking on cancel button

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1641]
Steps to replicate:
1. Open Manage Groups option
2. And click on cancel button
for a while it displays like below

![managegroup_cancel](https://cloud.githubusercontent.com/assets/10941328/9349984/175ba064-466a-11e5-99c1-c80786fe14b8.PNG)

**Comment by gordonwoodhull** [comment]
@anatoliyg, it must be clearing the model as it closes the dialog? there are a couple of different events to link to (*hide vs *hidden), maybe it would be better to tie destruction to the later one.

anyway, this is just an annoyance, not something we need to deal with right away. i think the dialog closes faster on OSX which is why we hadn't noticed this before.

**Comment by anatoliyg** [comment]
I think you're right. I'll just clear the models when the hiding is complete
