### ISSUE TITLE
Different behaviors while forking any folder multiple times

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1643]
* While forking the any notebook folder multiple times from our own notebook tree, a copy of that folder gets created each time with incremented postfix in folder name

![fork1](https://cloud.githubusercontent.com/assets/9251570/9350330/781bb922-466d-11e5-93f1-019bbe8d4cd9.PNG)

* However when we fork any notebook folder multiple times from other user's notebook tree, the new folder doesn't get created each time instead it creates multiple copies of the notebooks in that folder without even incrementing postfix number in their names

![fork](https://cloud.githubusercontent.com/assets/9251570/9350331/7df33c62-466d-11e5-85f9-ae95360afaee.PNG)

**Comment by gordonwoodhull** [comment]
This is really an instance of #703, closing as duplicate. 

Due to a GitHub race condition we are not able to fork someone else's notebook and then immediately rename it - the fork doesn't seem to have completely committed, even though we've received a success message. GitHub support suggested a 1s delay, which is unacceptable, so keeping the duplicate notebook/folder names for now.
