### ISSUE TITLE
allow more cell lines to show (when there is only one cell)

### ISSUE THREAD

**Issue by holyguster** [att/rcloud#1654]
This issue is based on user feedback.

When working with notebooks that require all my code to be in one cell (like mini.html or notebook.R), only seeing ~31 lines in edit mode is a little annoying.  Once a cell is executed, the RCloud UI shows me all the lines of long code cells (75 lines, 100 lines, etc), but when I click to edit the code, it shrinks down to ~31 and adds a scroll bar.

Is there a reason to limit to the number of rows when editing a cell?

**Comment by gordonwoodhull** [comment]
I think there is a design issue if RCloud libraries are forcing anyone to put all their code in one cell, but nonetheless, I agree. 

It may not be obvious, but having a cell that's taller than the notebook div on the screen may not work. I think the best solution is to have one cell that fills the entire notebook div and scrolls internally, and I filed this earlier as #662.

Alternately, what we could do as an intermediate fix is to increase the maximum size of an active cell so that it's dependent on the height of the browser. This would be easier to implement (and reason with).

**Comment by gordonwoodhull** [comment]
Around RCloud 1.7, we eliminated two-level scrolling. A tall cell is shown in its entirety.
