### ISSUE TITLE
Conversion of encrypted notebooks to public fails silently on public GitHub

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1665]
Steps to replicate: (only on RCloud local instance )
- Assign any notebook to any group or make it private
- Upload any binary asset to that notebook
- Make that notebook public again
- Try to rename the asset

Session div will throw following error

![private_to public_error](https://cloud.githubusercontent.com/assets/9251570/9900607/85e3bd02-5c7f-11e5-9a3a-d01d5bb9cb3d.PNG)

Following error is thrown when any asset is deleted 

![privet](https://cloud.githubusercontent.com/assets/9251570/9900697/16224ac8-5c80-11e5-97a7-d79f0a762f40.PNG)

**Comment by s-u** [comment]
Can you, please, define what you mean by "local only"? What exactly is the setup (SKS, GH, proxy, CS, ...). Thanks.

**Comment by prateek05** [comment]
I think "local only" is a Ubuntu 14 on Oracle VMBox, SKS 1.3, Public GH, No Proxy , No CS(Requires Proxy). It s just Ubuntu, R 3.2 , SKS 1.3 and RCloud (Single User) @sanketd11  correct if the setup is different

**Comment by sanketd11** [comment]
Ya it's the same setup as mentioned by @prateek05

**Comment by gordonwoodhull** [comment]
I'm able to repro this on my local instance but not on rcloud-2. I would guess that it's a public github issue since the software on public github tends to be "ahead" of enterprise github.

**Comment by s-u** [comment]
Two underlying issues here:

 - GH request to update a notebook from encrypted to plain fails silently, i.e. no error is shown
 - public GH didn't like the way deletion of the encrypted version of the notebook was specified in the request (with `name:{content:nil}` instead of `{name:nil}`)

what you really see is just the follow-up inconsistency where the notebook is actually still encrypted but RCloud  thinks it's in plain text so all kinds of things just break.

**Comment by s-u** [comment]
BTW: one good way to check the root cause when encrypted notebooks are involved is to use "Show in GitHub" to see what is actually stored threre.
