### ISSUE TITLE
WDCPlot under rmarkdown and compute separation

### ISSUE THREAD

**Issue by robert-a** [att/rcloud#1676]
When running WDCPlot in an rmarkdown cell in RCloud running Compute Separation an "@" is used by RCloud that is causing rmarkdown to interpret the string as an email id. It is causing the computer to open an email message each time the User clicks on the plot.

**Comment by gordonwoodhull** [comment]
Thanks @robert-a. I think this must be a problem with particular versions of pandoc or rmarkdown, because I think I saw it in the past but can't repro on rcloud-5 which has compute separation and the `@` in its deferred result tags. Where are you seeing this?

It's really kind of a dumb policy to replace everything that has an `@` in it with an email link. All the documentation I can find says that pandoc should only be looking for these forms:

```
[myname@gmail.com](mailto:myname@gmail.com) 
<myname@gmail.com> 
```

**Comment by gordonwoodhull** [comment]
Hmm, actually I'm able to repro for other links but not ones that are in code tags, as the generated output is. I.e. I get output that looks like this:

![image](https://cloud.githubusercontent.com/assets/1366709/10144764/5a3aa72a-65ed-11e5-98c9-14dc9e3a23d6.png)

.. because RMarkdown escapes to standard R printing for any embedded code, so it's printing the deferred result as a value just like it would print `## 0`, and then the charts get substituted inside the `code` block.

Does your output also look like that?

**Comment by robert-a** [comment]
Here is what I see:

[cid:image001.png@01D0F9FB.0A51E0B0]

**Comment by gordonwoodhull** [comment]
Hmm could you post that in the web interface? I don't think github picks up attachments from email.

**Comment by gordonwoodhull** [comment]
@robert-a wrote:
![image](https://cloud.githubusercontent.com/assets/1366709/10145084/0e16712e-65ef-11e5-8d7f-b690c12ff493.png)

**Comment by gordonwoodhull** [comment]
I'm convinced it's a bug in rmarkdown and we aren't going to be able to do anything unless we stop pandoc, and I can't find any documentation about what it's doing. It occurs when the output is qualified like this: `{r results="asis"}`

**Comment by robert-a** [comment]
When I remove the results="asis" I get the “##” instead of the big string and the email problem.

However, now the WDCplot shows up in a code block!

[cid:image002.png@01D0FA02.F157B500]
