### ISSUE TITLE
Once a member is promoted to Admin, next time the member vanishes from the Group itself

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1696]
Steps to replicate:
1. Open existing group, add single member to it and click on 'OK'
2. Now open 'Manage Group' and remove the member and make him admin and click 'OK'
3. Again open the 'Manage Group' option, only single admin is visible ( the earlier admin)

**Comment by gordonwoodhull** [comment]
gee whiz, how did we miss this?

**Comment by gordonwoodhull** [comment]
@anatoliyg, the issue is that we effectively have different add-admin and add-member, but only one remove-from-group. We execute the member changes after the admin changes, so the remove member deletes the admin.

Please simply filter the `removeMembers` to not contain any of the `addedAdmins`.

I don't *think* we should see other conflicts between the members and admins, but it's worth thinking about. It would probably be smarter to send the vector of changes to the back-end and do any logic there.

**Comment by Prateek032** [comment]
This issue is still reproducible on  Local instance (release-1.5 branch/ edc6bb0 )

**Comment by anatoliyg** [comment]
strange...  @gordonwoodhull do you think it could be something else? I have removedMembers filtered to not contain any of the addedAdmins...

var removedMembersTemp = _.difference($scope.originalMembers, $scope.groupMembers);
var removedMembers = _.difference(removedMembersTemp, addedAdmins);

**Comment by gordonwoodhull** [comment]
Weird, I tested this in the debugger and it worked. Investigating.

**Comment by gordonwoodhull** [comment]
@anatoliyg, it's because you duplicated the logic from `saveGroupTab` into `getCurrentChanges` and then only fixed it in `getCurrentChanges`, which is only used for the display. It's always a bad idea to duplicate logic just for display reasons. Please fix.

**Comment by anatoliyg** [comment]
facepalm... think it got lost during commit.

 yea ill fix it to reuse the code
