### ISSUE TITLE
Forking doesn't create a new copy of the notebook

### ISSUE THREAD

**Issue by prateek032** [att/rcloud#1715]
Steps to replicate:
1.Fork any notebook from other users notebook tree
2. Edit the forked notebook by adding cells to it and save the notebook
3. Now delete the notebook 
4. Fork the same notebook again
The Forked notebook contains the previously edited contents of the Notebook instead of creating new copy of the Notebook

**Comment by gordonwoodhull** [comment]
Thanks for reporting this, @Prateek032. 

This is a known issue, again due to Github's policy of only forking once. You in fact receive the same deleted notebook, which has not actually been deleted from Github, but only removed from the RCloud catalog.

The workaround when this happens is to Open in Github the notebook, delete it there, and then fork the other user's notebook again.

We are open to suggestions how to make this easier. It is our own policy not to truly delete notebooks, because there may still exist links to them and we generally don't want to lose code.

**Comment by s-u** [comment]
This is worse that I expected - it essentially makes collaboration hard since you can't follow changes someone else is making. The only way to work around it would be to use our own metadata just as we do for `gitgist` an create a new notebook with overriding `forkof` information.

Given how much we're working around limitations in GH, I'm really inclined to ditch it and invest in the server on top of `gitgist` instead.

**Comment by gordonwoodhull** [comment]
Yes. It means ditching the notebook history, but I guess we're forced to do it.

**Comment by s-u** [comment]
Yes, in the case of forking the history is less of an issue, since it still exists in the forked notebook and you have a direct link to it.

**Comment by s-u** [comment]
BTW: we should also consider having a true "delete" such that deleting a notebook actually deletes it - including on GH. We could make it an option for now and change the default later.

**Comment by gordonwoodhull** [comment]
If you combine shallow forking with true deletion, history really will be lost.

**Comment by s-u** [comment]
We could limit the deletion to non-forked notebooks. Essentially the context in which the deletion came up was that our GH is filling up with a lot of garbage (one-line test notebooks and such) that will show its ugly face if we ever have to restore notebook metadata from GH. That's low priority but something to keep in mind.

**Comment by gordonwoodhull** [comment]
Maybe for 1.6 it would be a good idea to warn the user that this is what is happening and provide instructions to delete from GitHub if they want a fresh fork?

**Comment by gordonwoodhull** [comment]
Added a warning/explanation for 1.6.

**Comment by gordonwoodhull** [comment]
Another workaround is to import the notebook instead of forking it. Use Advanced / Import External Notebooks. Specify the same Github server that your instance is using, and the notebook id. It will be copied instead of forked.

**Comment by gordonwoodhull** [comment]
This is solved for us by using [rcloud-gist-services](https://github.com/att/rcloud-gist-services).

Since we can't do anything about GitHub's gist implementation, closing this.
