### ISSUE TITLE
Users who have changed their Github usernames

### ISSUE THREAD

**Issue by prateek05** [att/rcloud#1754]
Should the user keys get rewritten if the rcs registered notebook keys username does not match with user$login. 
What about the user keys in rcs? 
Mine changed in GHE. I could find 50 more instances in IT. 
Prateek

**Comment by s-u** [comment]
Changing usernames is not supported, GitHub explicitly warns about that and as far as RCloud is concerned it is not legal to do so. GH also warns about the metadata inconsistencies it creates so I don't think we want to open that can of worms - we could display a warning that the account is locked until you restore the original name.

**Comment by martymcwizard** [comment]
ok.  we got confused because the github admin interface allows us to rename.  It's ok. For our instance we must align users with their IDs so it looks like the plan will be 1) take away self-provisioning (since users were not following instructions on naming their accounts with their IDs), 2) suspend all misnamed accounts, 3) download their notebooks, 4) delete their account, 5) create a new account with  their correct ID 6) upload their notebooks to their new accounts.  I'm glad we caught this while there was just a handful.  It is my experience that when we delete an account out of github then the notebook tree no longer shows the user.  I'll validate and reach out if that doesn't work out.

**Comment by s-u** [comment]
You can migrate notebooks, the easiest may be by forking. As far as RCloud is concerned it's ok to have both names in GH - it may be worth testing all the different options such as suspending the old usernames. If you delete them I wonder what happens to the fork links. With a mass-migration like that I'd first check the behavior on a test account before actually doing it ;). Also you'll have to be careful with things like the search - it will definitely have the old usernames and if you delete a user and all its gists the search results will become inaccessible.

**Comment by prateek05** [comment]
Github allows renaming user ids. The gist hash remains intact so forks and other references get updated at GH's end. As a bonus GH also keeps redirects from older remote urls and profiles to newer one for a temporary period of time. At GH's side things remain consistent. At our side any info previously mirrored creates a problem. 


As simon stated deleting previous accounts rather than renaming will lose a lot of information. 
Prateek
