### ISSUE TITLE
Move "Help" and "Search" to the right pane

### ISSUE THREAD

**Issue by s-u** [att/rcloud#1802]
I have seen too many users constantly resizing the Notebook pane because of the Help/Search panes blowing up the Notebook pane and this obscuring the notebook itself. We should move the Help/Search panes to the right side where they belong and are compatible with the wide size of the Assets.

(Yes, I'm pretty sure this is a duplicate but can't find it and I'd really like to keep this very specific so it gets done :))

**Comment by gordonwoodhull** [comment]
Yes, this is #527 and #447

It should be an option, and what we've previously discussed is moving the small panels (comments and file upload IIRC) to the left side so it doesn't get too crowded. 

I *think* I did all the groundwork for this already, so I'm okay with scheduling this for 1.6.

**Comment by gordonwoodhull** [comment]
Option can be checkbox "Arrange Panels by Size" or something like that, swaps comments and file upload with search and help.

**Comment by shaneporter** [comment]
I can see that swapping of panels between left/right whilst changing the state of a control in a left-sided panel (albeit one that isn't directly affected by the swap) would be disorientating for the user.

I don't have an alternative to 'Arrange Panels by Size' ('Arrange Panels so they don't annoy you as much' isn't really feasible), but would it not be an idea to just swap them and be done?

Not everybody is a fan of change, but it seems that the majority would welcome it, and everybody would get used to it.

**Comment by gordonwoodhull** [comment]
Since most of our UI configuration is at boot time, we don't bother to change the interface on the fly for many options. For those options "reload to see changes" appears in red in the lower right corner when the option is changed.

I agree, it's probably not necessary to have an option, but it's easy to add the option, default it to the new layout, and then remove the option if no one opts out.

I think the old layout ("arrange panels by purpose"?) works okay on really big monitors.

I also like having the option because if users compare layouts them they come up with even better ones.

**Comment by shaneporter** [comment]
How will we know if no one opts out?

**Comment by gordonwoodhull** [comment]
All options go to [RCS](https://github.com/att/rcloud/wiki/RCS) so it's easy to determine how many people use each option. Actually, we currently have no security on RCS so one could write a notebook to analyze this, and we could hide some of the old options if no one is using them.

**Comment by shaneporter** [comment]
Interesting, thanks!

**Comment by shaneporter** [comment]
PR #1982 addresses this issue.

**Comment by gordonwoodhull** [comment]
Implemented in #1982
