### ISSUE TITLE
Cell deletion is not working

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1822]
Steps to replicate:
1. create a new notebook with more than 1 cell
2. Now select all  the cells and click on delete icon
3. Click on create new notebook
4. then switch back to previous notebook

**Comment by gordonwoodhull** [comment]
Instead of steps 3 and 4, just reload the page.

Probably what is happening here is that the changes are not committed - all other actions in the notebook controller that modify the notebook do a little "update notebook then default callback" dance afterward. So the model is probably inconsistent with the state of the gist.

**Comment by shaneporter** [comment]
crop and delete multiple should now be dancing.

**Comment by gordonwoodhull** [comment]
Fixed by #1832
