### ISSUE TITLE
Esc <esc> key doesn't work properly for Editable titles and some dialog boxes

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1831]
- [x] The dialog box for import external notebook disappears after pressing Esc key. Similar behavior is not reproduced by group management dialog box. 
- [ ] Similarly for editable titles, the title field should go out of focus when Esc key is pressed. But currently after editing the notebook titles, if we press Esc key, it seems to be gone out of focus but the focus remains there.

**Comment by gordonwoodhull** [comment]
Thanks @sanketd11. I remember there was some reason why Anatoliy didn't enable esc for the group management box. I can't remember it but let's enable it to see if is a problem.

**Comment by shaneporter** [comment]
Not sure if there _was_ an issue here, perhaps fixed by e694e6f.

- The Group management dialog, like others, can be closed by pressing `esc`.
- Editable titles go out of focus when the `esc` key is pressed.

**Comment by gordonwoodhull** [comment]
The dialog one is fixed. 

The editable title problem is still there. The first key typed after `esc` selects the title again, and then the second key starts replacing the title. I am not sure it is a huge problem, because where should the focus go? I guess we could set it explicitly to focus on the document.

**Comment by gordonwoodhull** [comment]
I'm not sure if PR #1911 / e694e6f has any effect here.

**Comment by gordonwoodhull** [comment]
Fixed by #1922
