### ISSUE TITLE
Check box should be disabled, if there are no cells present

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1834]
User can select the check box for once even if there are no cells present in the notebook

**Comment by shaneporter** [comment]
I'd say we can go further and disable the check box, drop down (all, none, invert) and delete button.

**Comment by gordonwoodhull** [comment]
My preference is for the checkbox also to be in the mixed or non-state (horizontal line) since it's indeterminate.

I don't think we currently have any logic that detects whether there are cells or not.

**Comment by shaneporter** [comment]
I've thought about this a bit more, and don't think we should use a non-state, since that is used specifically for 'some but not all selected'. In the case where there are no items, and hence no selections, the unchecked state should be used.

![image](https://cloud.githubusercontent.com/assets/2493614/13751648/0cc40a82-ea03-11e5-8aa7-feace85b6c63.png)

Gmail uses an unchecked state checkbox when there are no items... and doesn't disable the clicking of the control to show the menu. Clicking on a menu item or the checkbox directly has no impact and the checkbox remains in an unchecked state.

**Comment by gordonwoodhull** [comment]
Okay, sounds good. I was probably being pedantic. A disabled empty checkbox will probably be more clear to most folks.

**Comment by gordonwoodhull** [comment]
fixed in #1843
