### ISSUE TITLE
display errors in mini and shiny, in particular for IE

### ISSUE THREAD

**Issue by s-u** [att/rcloud#1845]
mini.html and shiny.html fail silently on unsupported browsers like IE. We should add code to handle that case by issuing a warning/error visibly so users are less confused.

**Comment by gordonwoodhull** [comment]
I believe we don't currently have a way to display any errors in mini.html or shiny.html. This comes from the "how mini is mini?" controversy (#1800) - originally mini.html and thus shiny.html had absolutely no UI at all, so it made sense that we didn't have a way to display errors.

Since we've slowly warmed to the idea that they should have some UI built in, enabling/including the Aw Shucks dialog makes a lot of sense.

I'm changing the title because this is more broad than unsupported browsers - it is all sorts of errors like bad notebook, unpublished notebook, connection error, etc.

**Comment by s-u** [comment]
Ok, makes sense. For this issue, I'd like to keep this in the scope of errors before the application is instantiated, since providing a full error handling API is a much bigger scope. That said, I still think the browser detection should be #1 before we even instantiate any session.

**Comment by gordonwoodhull** [comment]
Okay, I'll make sure we are checking `browser !== IE` however I'm not aware of any error reporting problem in mini and shiny aside from the lack of UI.

**Comment by gordonwoodhull** [comment]
@shaneporter, please see if doing a `fatal_dialog` in `session_pane.post_rejection` is enough to handle wrong browser, dependency problems, and notebook errors all.

**Comment by shaneporter** [comment]
I have added a catch clause following `rcloud.call_notebook(...).then(...)` in `mini.js` which is now catching more errors that were previously being dumped to the console.

So, am I right in my understanding that for this work:

- IE is not supported so immediately alert the user that they should use an alternative, supported browser.
- Any errors should be shown using the existing `fatal_dialog` code. (I am not sure what you mean by `session_pane.post_rejection`, because we don't have that panel in the minimal UI in mini/shiny.)

**Comment by gordonwoodhull** [comment]
Yes, that's right about IE. 

Okay, my memory about `session_pane` was probably wrong. The object always exists (it's a global) but we do not initialize it if there is no UI.

Nonetheless, all error handling goes through there. (Horrible, I know.)

If we initialize it, then we tell bluebird to send all unhandled rejections through there. So there should be no need for specific catch handlers. Any uncaught exception inside a promise will land here automatically. (And almost all client-side code is wrapped in a promise.)

So I think we should initialize it in all modes. (Explicitly adding `session_pane.init()` to shiny and mini, as it is in discover and view already.)

There are currently two cases: it looks for `#session-info` (edit) and it looks for `#output` (view). If both of those fail, it should go into a mode where errors go to `fatal_dialog`.

**Comment by shaneporter** [comment]
Thanks. I had an error in my notebook, and it wasn't being handled by the code.

**Comment by shaneporter** [comment]
A suggested fix has been submitted with PR #1995.

**Comment by gordonwoodhull** [comment]
@shaneporter, I finally got around to spawning my VM - it doesn't seem to detect either Edge or IE. Does this work for you? I forget what platform you work on.

**Comment by gordonwoodhull** [comment]
(It could be that a later commit invalidated this too.)

**Comment by shaneporter** [comment]
I work on Ubuntu. With a (much) preferred browser choice of Chrome.

**Comment by gordonwoodhull** [comment]
Heheh. They say Edge is "actually pretty good" but I think it's going to be pretty hard for anyone to believe that after all these years...

**Comment by gordonwoodhull** [comment]
Do you have access to Windows 10 to test this? I can take it if not.

**Comment by shaneporter** [comment]
Not readily, no.

**Comment by gordonwoodhull** [comment]
Okay, no problem. Always love booting up that VM to install the updates and reboot.

**Comment by gordonwoodhull** [comment]
Ah, this does work! I was just testing it with edit.html. We should display the same message in edit.html and view.html.
