### ISSUE TITLE
Unable to find the saved cell content with Find/Replace

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1849]
Steps to replicate:
- Add some content to a cell
- Invoke Find/Replace feature
- Try to search the cell content
- Save the cell contents
- Try again to search the saved cell content

Find/Replace feature will not highlight the content even though the content is present in the cell

**Comment by shaneporter** [comment]
I'm seeing that after the find (or find/replace) feature is invoked, newly added content isn't 'found', regardless of whether that cell's content has been saved.

Only closing and reopening the find (or find/replace) feature 'recognises' the new text.

**Comment by shaneporter** [comment]
Seems like there's an issue with the `content()` return value being 'stale'. I've managed to quite easily create something like this:

![image](https://cloud.githubusercontent.com/assets/2493614/14789873/8ea6ec3a-0b06-11e6-9f1d-f111f329505f.png)

**Comment by gordonwoodhull** [comment]
Yeah, I don't think there's any attempt to keep the search results updated when the notebook changes. It's one of those loose ends I noticed right before a release and then completely forgot about.

Looks like the dirty bit handling in notebook_controller needs to provide an event that the find/replace logic can listen for. Then I guess the entire search needs to be recomputed. This might be slow, so a delay or throttling might be needed so that it's not doing a lot of work on every keystroke when the notebook is large.

**Comment by shaneporter** [comment]
I don't know whether the search needs to watch for notebook changes. If I do a search right now on this page as I type, it matches what's currently there. If I type some more text, it doesn't update its search until I click the 'next' or 'previous' buttons.

**Comment by gordonwoodhull** [comment]
This was not fixed by #2033
