### ISSUE TITLE
Redirecting user to the login page instead of showing Session logged out message

### ISSUE THREAD

**Issue by NaikPrateek** [att/rcloud#1923]
Steps to replicate:
1. Open any published notebook in view.html as anonymous user
2. Click on 'edit' icon, session reconnect message appears
It would be very helpful for user, if we redirect them to the login page instead of showing  'session reconnect' message

**Comment by gordonwoodhull** [comment]
True, although the message is accurate, this is not a very friendly approach.

I think we would have to do an automatic redirect whenever navigating to a page that requires login. Because the edit button just navigates to a page, so it's the same case as if you had a bookmark to the notebook, or you clicked on a link in an email.

**Comment by gordonwoodhull** [comment]
As of 1.6, navigating to `edit.html` redirects to login without displaying any annoying message. It's not perfect but it mostly seems to work.
