### ISSUE TITLE
"aw shucks" is white in shiny.html

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1956]
![capture](https://cloud.githubusercontent.com/assets/9251570/15036647/dd783570-12af-11e6-8f72-2495408b56a6.PNG)

**Comment by gordonwoodhull** [comment]
Hmm, adding rcloud.css to shiny.html breaks other things. There is a reason we didn't. 

Notice the fatal dialog alignment is off and it also makes one of the select elements huge.

We probably would need a minimal CSS that just styles this dialog.

![image](https://cloud.githubusercontent.com/assets/1366709/15074489/58e4927c-136d-11e6-9b0d-3effccb3ae71.png)

**Comment by shaneporter** [comment]
What's the simplest shiny notebook I can use to replicate this issue? When I invoke the fatal dialog on shiny.html using `RCloud.UI.fatal_dialog`, I see this:

![image](https://cloud.githubusercontent.com/assets/2493614/15109683/8e14dd3a-15d4-11e6-821d-0af9f25f7401.png)

I'm not concerned about the `undefined`, but there is _no_ styling because no CSS resources are requested. Perhaps I'm doing something wrong.

**Comment by sanketd11** [comment]
Try with following steps:
- Open any shiny notebook with Shiny.html  
- Kill the Rserve
You will get the dialog this way

**Comment by shaneporter** [comment]
@sanketd11 thanks, I can simulate an issue by invoking the fatal dialog from the JavaScript console. I was wondering about a minimal shiny notebook. Do you have one you could attach?

**Comment by gordonwoodhull** [comment]
Was about to write the same thing. 

Shiny will dynamically load the bootstrap css and a bunch of other dependencies, so that might explain the unformatted output you saw.

**Comment by gordonwoodhull** [comment]
Can't think of a fatal error that will occur from within Shiny, we pretty much just let them take over.

**Comment by shaneporter** [comment]
thanks @gordonwoodhull can you please attach an exported notebook that you used for the screenshot above?

**Comment by gordonwoodhull** [comment]
Better, all the supported Shiny notebooks are on rcloud.social and you can use the same notebook ids on your own instance if public github is your notebook store.

http://rcloud.social/edit.html?notebook=68d114c159e5c364ae7e#

**Comment by shaneporter** [comment]
My `shiny.css` file is under `/usr/local/lib/R/site-library/shiny/www/shared`. Has it come from a package that I've installed? rcloud.shiny? How do I edit the source code for this package (for the dialog)? It seems to be independent of RCloud core.

**Comment by gordonwoodhull** [comment]
Right, we allow Shiny to install all its own resources, and we can't really edit any of them.

Anything we customize has to be in the shiny.html shell. Then we boot up Shiny and insert its entire content into shiny.html. At least that's how it works now - in the long run it might be better to blend our startup code with theirs.

I don't think this issue is really worth any effort. But it's worth learning how the rcloud.shiny system works.

**Comment by shaneporter** [comment]
OK, thanks.

**Comment by gordonwoodhull** [comment]
Fixed by #2106
