### ISSUE TITLE
Interested in a Vagrant config for Rcloud?

### ISSUE THREAD

**Issue by gaborcsardi** [att/rcloud#1970]
I created one here:  https://github.com/MangoTheCat/rcloud/tree/vagrant/vagrant and of course for me it would be easier if this could be added to the main ATT repo. :)

Thanks!

**Comment by prateek05** [comment]
@s-u A installer/deployment directory having vagrant and docker scripts ? For folks who want to deploy as an application container ?

**Comment by gaborcsardi** [comment]
I started using it and it needs some refining, so not ready to be merged yet. In particular:
- I should create a swap file on the guest,
- rcloud should be run as non-root
- It would be nice to have some script(s) to restart/redeploy, etc. the guest installation.

**Comment by gordonwoodhull** [comment]
I think this would be great. Deploying RCloud is still too hard, because of the enormous number of dependencies. We are frequently asked for an easier solution.

However, it will be hard to get right, and IMO we'd want it to support some of the more difficult configuration options like:

 - multi-user 
 - proxy

out of the box.

**Comment by gaborcsardi** [comment]
This config is mainly for development. Hence the shared folder with the host for example. Deployment probably requires another config.

**Comment by gordonwoodhull** [comment]
I see. Maybe we could target it as a single-user "try me" config - a step up from development but not production-ready. (As if RCloud is ever production-ready. /s)

I accidentally checked this in once (from one of @paulinshek's PRs) and then removed it. I don't think it does any harm to keep it around since it's just a directory of stuff. @gaborcsardi, please do a formal PR for this and refine it to where you are somewhat comfortable with it.

**Comment by gaborcsardi** [comment]
While this works for me, and I am using it for development, I don't necessarily want to spend time on improving it, so I'll close this PR now.
