### ISSUE TITLE
second column of shortcut dialog does not display on smaller screens

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2006]
we now have enough keys so that it's filling up and some of the keys are not visible unless you scroll.

but it looks like there's room for a second column of shortcuts.

this will really help when we merge #1903 ace shortcuts.

i'm not sure how hard this is (or if there's really enough room) so not putting it on a milestone yet

![image](https://cloud.githubusercontent.com/assets/1366709/15733358/3ee39efe-2853-11e6-8773-d0bfa7b15e55.png)

**Comment by gordonwoodhull** [comment]
So yeah, I see that a second column does open up if the window is wide enough. Just not enough space on my macbook.

I fear that not everyone will find all the content if we have scrolling within a dialog, especially on a Mac where the scrollbars are hidden by default. But I know pagination is a lot of work for very little benefit. Maybe we can just make the content narrower for 1.6 so that it fits on smaller screens. Looks like it's the big gap between keys and descriptions which is causing this for me.

**Comment by shaneporter** [comment]
What's the resolution on your laptop @gordonwoodhull? Just so I can see exactly what's going on.

Aside from anything else, the shortcut dialog looks ugly on your system. No so bad for me on Ubuntu, but clearly there are major improvements to be made. I think tabs by category would be a good way to go.

**Comment by gordonwoodhull** [comment]
I've got a 2015 macbook so I think the emulated resolution is usually 1152x720. I don't think we'll have to go any smaller than that. 

Tabs rather than paging sounds like a good solution. Although I think we should be able to squeeze monow into the layout than we're getting now.

**Comment by shaneporter** [comment]
Thanks. Does _monow_ mean more?

**Comment by gordonwoodhull** [comment]
I have no idea what monow means 😄 but I meant more. Heheh.

**Comment by shaneporter** [comment]
Thought it was an Americanism, but Google offered nothing. Thanks for the clarification. :smile:

**Comment by shaneporter** [comment]
As I mentioned in #2015, I was inspired by Github's help dialog.

Because RCloud's main window doesn't scroll, I had to adopt a scrolling dialog body approach. Even with tabs, a category's content may not always fit within a fixed size body.

On non-macs, the scrollbar is fairly obvious, but perhaps not so much on OS X. Perhaps if I show a 'Scroll for more' message in the bottom right of the modal for a short period (or disappear when the content is scrolled)? Not ideal perhaps, but it means that:

- user will be aware that there is more content;
- scolling modal body content is much more flexible and future-proof, as new shortcuts are added.

Let me know your thoughts @gordonwoodhull. Thanks.

**Comment by gordonwoodhull** [comment]
Sure, that sounds like a decent approach. I'm not remembering what icon all those snazzy new sites use when it's not clear that you should scroll, but we should use that. It's really a discoverability issue; once I learned that I could scroll it seemed natural to me. 

Still wish that we could squeeze it just enough to fit a second column on my screen, but that's probably greedy of me.

**Comment by gordonwoodhull** [comment]
fixed by #2063
