### ISSUE TITLE
discover page relying on editor_tab's load_everything() for metadata

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2027]
That is, `load_everything()` via `editor.get_notebook_info()`.

`load_everything()` currently loads the starred notebooks of the current user, as well as the featured notebooks. It's the wrong data for the discover page, and inefficient.

Discover probably can just keep its own `notebook_info_` and stars instead, and populate it based on the results it is using. There is nothing particularly complicated about what the notebook tree is doing here, so no reason for it to own that data.

**Comment by paulinshek** [comment]
@gordon, I have been thinking about how to do this and I don't think my initial idea of copying the code across to a new discover-tab.js is the best idea... it would be very difficult to maintain due to the duplicated code.

Another idea I have, is to instead focus on modularising editor_tab and shell_tab instead? I think it could be split into "meta information", "notebook tree", something like that? And then the discover page probably only needs "meta information"? What do you think?

I'm hesitant to do this whilst other changes are being made to the discover page at the same time, especially as I don't know the code very well! I'm going to prioritise the bug fixes first, if that's okay?

**Comment by gordonwoodhull** [comment]
Sure, makes sense to deal with the other stuff first. 

I don't think any code needs to be copied, in fact there isn't really much code needed at all. You just need to get rid of the references to `editor_tab` and instead load the infos and stars for the notebooks in the list. So it should just be a call to `rcloud.get_multiple_notebook_infos` and a call to `rcloud.stars.get_multiple_notebook_star_counts`, much like `get_notebooks_by_user` does in `editor_tab.js`. 

Basically the mistake that was made was to treat `editor_tab` as a database of notebook information, when the operations it's doing to populate that information are very simple and it is no longer comprehensive due to #1901. Sometimes encapsulation leads to mystification.

But anyway, no rush, although it's something we have to deal with. I'm surprised we haven't seen any crashes yet, since any popular notebook which is not a sample notebook or starred by the current user will be missing.

**Comment by paulinshek** [comment]
Oh! This is much simpler than I thought!
