### ISSUE TITLE
Error In discover page

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#2036]
1. Delete all the notebooks that are displayed in the recent tab of Discover page
2. Load discover page
3. Now click on 'Popular' option twice following error is displayed in discover page

![image](https://cloud.githubusercontent.com/assets/10941328/15817745/20718dee-2bf7-11e6-8861-a59b11f7933b.png)

and some times this error

![discovererror](https://cloud.githubusercontent.com/assets/10941328/15817773/490419b6-2bf7-11e6-8b55-6024b60473c0.PNG)

**Comment by gordonwoodhull** [comment]
I saw the first error without performing steps 1 and 2. My hunch is that it occurs when #2025 does not occur, i.e. when the bootstrap radio buttons load correctly. (Could be wrong, often am.)

The second error looks like it may happen because there are no notebooks to display in the recent notebooks "tab" (what do we call these?). And indeed, I was able to reproduce it because I decided to change the key under which the recently modified notebooks are stored.

**Comment by gordonwoodhull** [comment]
.. and I've fixed the second one.

**Comment by gordonwoodhull** [comment]
I've confirmed that the first one happen when the radio buttons are properly bootstrap-initialized. Apparently bootstrap will send a changed message even when the radios haven't changed. 

That's fine, but why does jQuery `$('input[name=metric]:checked')` now return an empty set? It clearly is still checked:

```js
$('input[name=metric]')
[<input type=​"radio" name=​"metric" value=​"recently.modified" autocomplete=​"off" checked>​, <input type=​"radio" name=​"metric" value=​"most.popular" autocomplete=​"off">​]
```

I will leave this for @paulinshek and @shaneporter to figure out.
