### ISSUE TITLE
Thumbnail image disappears from 'Discover' page after any changes in 'Assets' div

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#2039]
Steps :
- Create a new notebook and save after adding contents to it
- Upload thumb.png image to assets div
- Load Discover page (the thumbnail image will be displayed on Discover page for that notebook)
- Now load the same notebook again and make any change in assets div e.g edit Scratch.R, add new asset, delete asset, etc.
- Open Discover page (thumbnail image will disappear)

The thumbnail image will not be displayed even if we undo the changes made in 'Assets' div.

**Comment by gordonwoodhull** [comment]
Thanks @sanketd11!

@paulinshek, I think this better explains #2011. Since we're looking at a *diff* of the notebook, not every update will contain the thumbnail. So we need to set the thumbnail when we see it, and not set it again unless it's explicitly null. (It will be the parent `thumb.png.b64` object that's null, not the `content`.)

**Comment by sanketd11** [comment]
The thumbnail also disappears if the notebook is assigned to any group or made 'private' but it reappears after making the notebook 'public'.

**Comment by paulinshek** [comment]
@gordonwoodhull Ah, good spot, thanks!

**Comment by gordonwoodhull** [comment]
Fixed in #2047
