### ISSUE TITLE
Unable to fork the Notebooks

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#2071]
Following error is displayed in session div, when we try to fork a new/old notebook

![image](https://cloud.githubusercontent.com/assets/10941328/16037375/cda21b0e-323d-11e6-983c-1303edededde.png)

**Comment by gordonwoodhull** [comment]
This is particularly on forking one's own notebook. Looks like we somehow are supplying a promise of a description rather than a string.

It would be helpful if you could copy the full text of the error rather than doing a screenshot. Some of the content is lost this way (and it's a very long error!) 

It also looks like we are screwing up the formatting on your platform.

I'll investigate both.

**Comment by gordonwoodhull** [comment]
Thanks @Prateek032!

Looks like we need to promisify everything that touches `find_next_copy_name` now. I'll take this.

**Comment by shaneporter** [comment]
Thanks @gordonwoodhull!
