### ISSUE TITLE
Unable to add  new member/admin to group

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#2092]
- According to current behavior, Member or admin can be added to group only if it is shown in the drop-down list below.
 
- But in current scenario while adding members or admins to any group, the drop-down list shows only those names that are already present as member/admin in the current group.

![image](https://cloud.githubusercontent.com/assets/9251570/16113178/12a90568-3389-11e6-9daa-ff8073b15736.png)

- If user want to add any other member to group, the list doesn't show that name thereby making it impossible for user to add new members

**Comment by gordonwoodhull** [comment]
I thought this used to work, but I can't find the call to `rcloud.get_users` that would enable it.

**Comment by shaneporter** [comment]
The code that gets the list of possible members is the return of the `getAllUsersinGroup` function. For what we're seeing, it makes sense.

@gordonwoodhull - Should the (selectize) dropdown suggest _all_ users for this? Seems so, but just checking, since I can't understand why `getAllUsersinGroup` was ever used.

**Comment by gordonwoodhull** [comment]
Yes. This is one of those bugs where I can't figure out how it ever worked.

**Comment by shaneporter** [comment]
I have opened a PR, #2105, for this.
