### ISSUE TITLE
hotkeys for replace actions

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2129]
Right now you click on replace and then can press enter repeatedly to replace each instance.

It's nicer to have keys for replace and next, like ctrl/cmd-R and ctrl/cmd-N. These would only be active within the find form.

**Comment by shaneporter** [comment]
[This explains why I couldn't get ctrl-N working on my PC](https://github.com/ccampbell/mousetrap/issues/172). I've always used ctrl-N for 'new', so mapping this to 'find next' doesn't seem ideal. 

Being a PC user, I tend to use f3 (or just enter, which is what we currently have) for 'next'. It seems 'enter' is used in this way on a Mac too (I've just checked with @gaborcsardi, because he uses a Mac.)

I'll implement the 'replace' shortcut as a start for this.

**Comment by gordonwoodhull** [comment]
Ah, good point. New Window is an important command and I don't grudge them reserving it.

And yeah, I guess we already implemented enter and shift-enter for next and last match. Please also map F3 and shift-F3 for Windows/Linux.
