### ISSUE TITLE
Notebooks I Starred should always be present in All Notebooks, even if owner deleted them 

### ISSUE THREAD

**Issue by amithrb** [att/rcloud#2165]
Deleted notebook visible under 'People I Starred' and 'All Notebooks' tree for other user.

Steps to Reproduce:
- User 1: Created new notebook 'a'.
- User 2: Starred that created notebook 'a'.
- User 1: Deleted notebook 'a'.
- User 2: Notebook 'a' is not visible under 'People I Starred' and 'All Notebooks' tree but visible under 'Notebooks I Starred'
- Notebook 'a' will be visible under 'People I Starred' and 'All Notebooks' tree, on clicking notebook 'a' which is visible under 'Notebooks I Starred'.

**Comment by gordonwoodhull** [comment]
Thanks @amithrb! As we discussed, it's intentional that starred notebooks will remain accessible to the user 2 who starred them, even after user 1 deleted them. We call it "removal" instead of "deletion" because we don't want to delete notebooks that people rely on.

The surprising thing is that these notebooks do not appear under All Notebooks / People I Starred for user 2. Those trees should always be a superset of Notebooks I Starred. 

I'll retitle this accordingly.

**Comment by gordonwoodhull** [comment]
This is confusing but not perilous, so I'm going to put it off to 1.6.1.

It is a regression from the 1.5 behavior (where we loaded the entire catalog so it wasn't really possible to have this kind of issue).
