### ISSUE TITLE
htmlwidget DiagrammeR doesn't work

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2169]
This one opens in another tab with an invalid URL. 

Presumably they are either not following the htmlwidget spec or we are relying on undocumented APIs.

**Comment by gordonwoodhull** [comment]
example from htmlwidgets showcase:
```{r}
library(DiagrammeR)
grViz("
  digraph {
    layout = twopi
    node [shape = circle]
    A -> {B C D} 
  }")
```

**Comment by gaborcsardi** [comment]
Interesting.

**Comment by gaborcsardi** [comment]
It has this code:
```r
    viewer.suppress <- !rstudioapi::isAvailable("0.99.120")
    htmlwidgets::createWidget(name = "grViz", x = x, width = width,
        height = height, package = "DiagrammeR", htmlwidgets::sizingPolicy(viewer.suppress = viewer.suppress))
```
which basically means that if it is not running in (that version of) RStudio, then it suppresses the viewer. And we use that viewer as well, to steal the output, similarly to RStudio.

https://github.com/search?q=user%3Acran+%22viewer.suppress%22&type=Code
gives you hints for what else is failing (from the widgets on CRAN at least): `chordNetwork` from `networkD3` and `profvis`.

I am not sure what we should do here, we might even consider these bugs in the widgets. They might want to avoid the RStudio viewer, but they should only do this if they are running in RStudio. I guess people don't anticipate other viewers. I can submit PRs to them.

A workaround for now could be something like
```
library(DiagrammeR)
d <- grViz("
  digraph {
    layout = twopi
    node [shape = circle]
    A -> {B C D} 
  }")
class(d) <- setdiff(class(d), "suppress_viewer") 
print(d)
```

You need to remove the `suppress_viewer` class. Unfortunately we cannot do this easily in `rcloud.support`, because there is a print method for the `suppress_output` class and our viewer is never called.

We could try to monkey-patch either these packages or the `htmlwidgets` package, but I am not sure if it is worth the trouble.

**Comment by gordonwoodhull** [comment]
I see - it's because we hook in at the RStudio viewer level, and these widgets think they won't have enough space there.

Sounds like we could submit a fix for DiagrammeR, but it wouldn't solve all widgets.

I can reproduce the problem with the networkD3 chordDiagram (the other suppressed diagram in that CRAN search), and the same workaround works. Maybe we should just document this limitation and workaround somewhere, but let's leave this issue open for now in case we come up with a better solution.

Thanks!

**Comment by gaborcsardi** [comment]
Another possibility is to add a function called `showHtmlWidget` that does the `setdiff` as above, and then just calls the regular `print`. We could put this in `rcloud.support`. It is trivial, and we can potentially use it for other fixes in the future. It is somewhat a glitch, though.

**Comment by gordonwoodhull** [comment]
Yeah, please just name it exactly what it does, like `reenable.widgets.viewer` or whatever, and we can hope that we don't need it for too long. 

Thanks for opening those issues and PRs on the other projects! Nice to see DiagrammeR already working.

We cover the whole Showcase but it might be fun to continue testing more of the Gallery to see if there are any other gotchas.

**Comment by gordonwoodhull** [comment]
Realized it was easier for me to just add `rcloud.view.recalcitrant.widget` than to have you create a PR for it.
