### ISSUE TITLE
Revert Notebook should be removed from the Keyboard shortcuts list

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#2220]
For read only notebooks (when we load any other user's Notebook) **`ctrl e`** is listed in keyboard shortcut window.

**Comment by gordonwoodhull** [comment]
I suggest adopting a more active flags-based design instead of just modes, "lifting" the flags support in the cell commands extension into `RCloud.extension` itself, and thus having the ability to enable/disable commands based on flag or !flag.

https://github.com/att/rcloud/blob/develop/htdocs/js/ui/cell_commands.js#L4-L37

**Comment by gordonwoodhull** [comment]
Specifically, Revert should be disabled when it's another user's notebook (and arguably when you're on the current version, although it's a no-op in that case). The logic that shows/hides the Revert button in the navbar seems to get it right, if a little complicated.

https://github.com/att/rcloud/blob/develop/htdocs/js/ui/configure_readonly.js#L8-L21

Maybe the navbar should be using flags too.

**Comment by shaneporter** [comment]
PR #2271.
