### ISSUE TITLE
Docker: Can't access RCloud after logging out

### ISSUE THREAD

**Issue by shaneporter** [att/rcloud#2256]
After issuing these commands on Ubuntu 14.04

````shell
docker pull rcl0ud/rcloud
docker run -d -p 8080:8080 rcl0ud/rcloud
````

I am able to use RCloud without an apparent issue. 

However, when I logout fully I am then unable to log back in. I have tried restarting the container, but the issue remains. It seems RCloud gets stuck in a loop.

**Comment by prateek05** [comment]
Yes, I see that sometimes. Something to do with the current tokens in the cookie, because if you go incognito the new session works fine. 
Prateek

**Comment by prateek05** [comment]
This is where the loop originates from
https://github.com/att/rcloud/blob/develop/htdocs/login.R#L48

The token is invalid and the loop starts with trying to check and then push back to the main page again. 

@s-u  Is it okay that we clear the token prior to redirecting ? Since check token has already established the token is no more valid.

**Comment by prateek05** [comment]
@gordonwoodhull raised a PR #2317  for the fix
