### ISSUE TITLE
firefox: can't click into notebook title or asset names

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2312]
When editing a `contenteditable`, it can be helpful to click a second time on the selected text to get to a particular character position. 

In Firefox, at least on OSX, this works in the `contenteditable`s in the notebook tree and comments, but not in the notebook title in the navbar, or the asset name-tabs.

**Comment by gordonwoodhull** [comment]
It may be that our own click handler is eating this. No idea why it would have higher precedence on Firefox than on Chrome.

**Comment by shaneporter** [comment]
I've spent some time on this, and although I don't have a fix, I do have a possible way forward.

I took a look at the events associated with the tree and notebook title/asset title. There were no differences of note. I then found this [Mozilla bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=419808#c5), and although it isn't _exactly_ the same, makes me think that the issue lies with a parent of the problematic contenteditables being an `a` element. (I tried the `draggable="false"` but it didn't work.)

If I change the `#rename-notebook' parent to a div (and style it so it looks as it did), the behavior in firefox is as it is in the tree! 

A solution could be to change the markup for the notebook title and assets, and change some css and event handlers.

**Comment by gordonwoodhull** [comment]
Thanks @shaneporter - I think we're only using an anchor to get some bootstrap styling. There isn't anything anchorish about it otherwise. A div with `display: inline` would be fine.

**Comment by shaneporter** [comment]
That's what I was thinking - just wanted to relay my findings. I'll go ahead and update.

**Comment by shaneporter** [comment]
PR #2326.
