### ISSUE TITLE
Error message spills outside of the box

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#2320]
Steps to reproduce;
- Open any history version notebook
- Copy the notebook Id (eg: `25458a622e71ee596d896f4a553ba697&version=df1e584a2cf0d32e8f760c8569816519b0f0ee4c`)
-  Open `Pull and Replace from notebook` and paste the copied content in `Notebook ID` field 
- then click on pull

![image](https://cloud.githubusercontent.com/assets/10941328/19800724/ab1b31d2-9d19-11e6-8b20-f6a9f91e1d6f.png)

**Comment by gordonwoodhull** [comment]
Thanks @Prateek032. That's invalid because the dialog only expects an id, not a fragment of a query string. 

So we should validate this field against a regexp and provide a more helpful error. 

But we should also consider adding a version field for the notebook id option, and parsing of the version for the URL option. Maybe not for 1.7 but as a follow-up.

**Comment by shaneporter** [comment]
Submitted a PR for this, #2329. 

I believe the 'version' work is split into a new enhancement issue, since it is outside of the scope of the initial 'pull and replace' enhancement changes.

**Comment by gordonwoodhull** [comment]
Thanks for the reminder, added another issue for later.

**Comment by Prateek032** [comment]
This issue is still reproducible on Firefox browser

![image](https://cloud.githubusercontent.com/assets/10941328/20171984/34a6c17a-a759-11e6-9777-2123eec49fec.png)

**Comment by gordonwoodhull** [comment]
Well, that's a different issue because it's the file chooser - I'll move it.
