### ISSUE TITLE
Close all cell output button on banner

### ISSUE THREAD

**Issue by LanceJensen-General** [att/rcloud#2334]
Please provide a mechanism to close a cells output without being at the top of a cell.  Log cell outputs can make closing them painful.

Another option could be to right click in the cell to have the option to close it.

Yet another option would be for the workbook to remember the state of cells and keep the output in the closed or open state.

I feel that the first option is the easiest to implement since it is literally a loop calling your close function on each cell or open function on each cell when invoked.

**Comment by gordonwoodhull** [comment]
Good idea. I agree, the first option would be the easiest to implement.

Now all we need is the right icon. 😏

**Comment by useless5771** [comment]
Could you confirm that the button should be added to the top-most navigation bar (where 'Run All' button is), please? The other option would be to add this new button to the "selection-bar", where you can perform operations on selected cells. 

The latter would let users not just to perform operations on all cells, but also it would be possible to hide/un-hide just selected cells results.

**Comment by gordonwoodhull** [comment]
Yes, absolutely the selection bar is the right place, since this is a global command on cells.

Interesting, I hadn't thought about hiding the results for selected cells. That could definitely be useful, for example in the case where there are a bunch of verbose cells which set things up, and then a few cells which do visualization - you could just keep the verbose cells selected and hide the results each time you run.

(We could even consider keeping those results hidden unless there is an error, in a future version of RCloud.)
