### ISSUE TITLE
R Cloud Shiny file access issue.

### ISSUE THREAD

**Issue by LanceJensen-General** [att/rcloud#2346]
During testing of our workbook app found here: https://rcloud.web.att.com/shiny.html?notebook=c17251a7ba93b3fe6dd5cf48b1c4732a 

A user received a file access error with the "Error in file: cannot open connection to file".  To test this issue I had the user open a new R Workbook in rcloud.web.att.com and list the file to be used in shell mode.  The list was successful.  Read was checked by doing a more.  The app would not run continuing to reject her.

I worked around the issue by making the file open to the world (766) and this resolved the issue.  We where able to do this due to Bobbie claim that  the data was derated and did not need to be secured.

**Comment by gordonwoodhull** [comment]
I don't understand what the issue is here. In the configuration used on rcloud.web.att.com, all notebooks run with the permissions of the current logged-on user. If run anonymously, they run as a special user (called "nobody" IIRC). 

So yes, any files accessed do need to have Unix permissions set so that any intended users can read them. Using Unix group permissions is another possibility.

**Comment by LanceJensen-General** [comment]
That is strange and unexpected because when I am developing the shiny application the workbook seems to have my user role access.  Based on what you said I should expect that it should have failed for me as well.  Is that correct?

Also if we make the notebook private to a group then it runs as the particular user?  If so, I will make that change to our testing to force group access to notebooks.

**Comment by gordonwoodhull** [comment]
There are two logins in RCloud, one to (enterprise) GitHub and one to RCloud. To reduce confusion on the rcloud.web.att.com instance, these logins have the same names.

The GitHub login controls access and ownership of notebooks (for editing). The RCloud login specifies the Unix user that owns the R process which runs notebooks. So the user specified by the RCloud login should have exactly the same permissions as if that user `ssh`'d to the server.

Hard for me to say whether you should or should not have access to that file, but I expect you'll find the same results via `ssh`. (Maybe there were already group permissions set?)

The notebook groups have no effect here - those just encrypt the notebooks so that they can be read by a group of (GitHub) users through RCloud. No relation to Unix groups here.
