### ISSUE TITLE
double scrollbar in dataframe viewer

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2484]
This may be a limitation of rcloud.htmlwidgets - I hope not. 

Either the widget iframe should scroll, or the viewer, not both.

![image](https://user-images.githubusercontent.com/1366709/32637613-dcf9aa38-c588-11e7-8e02-5894378caf21.png)

**Comment by useless5771** [comment]
Yes, I looked at it for couple hours when I worked initially on using DT as dataframe viewer and tried couple of possible solutions, but either of them worked properly: or iframe was not displayed at all, due to missing height, or there were no scrollars at all, or, if there was just the container's scrollbar, user could not scroll down the table, because table is in yet another container.

I will have another look, I will need to rearrange the structure of dataframe viewer and/or modify htmlwidgets package, e.g. modify the listener that (re-)calculates htmlwidgets heights.

**Comment by gordonwoodhull** [comment]
I was afraid you'd say that. Well there's no turning back now. Even if it means adding a hacky flag to rcloud.htmlwidgets, I think we'd better fix this, because it's pretty difficult to use this way.

One other possibility to consider is somehow gluing the iframe to the viewer, so that all the scrolling is inside the iframe. This feels clean to me, but of course it's a completely different model from how rcloud.htmlwidgets is embedded in the notebook. :-/
