### ISSUE TITLE
Is Github a hard requirement for RCloud deployment ?

### ISSUE THREAD

**Issue by aschmu** [att/rcloud#2615]
Hello, 
from the following page https://rcloud.social/documentation/ it's not clear to me whether Github is an absolute necessity for notebook hosting. If not what are the alternatives ? 
The following seems to suggest that only access through Github is implemented : https://www.youtube.com/watch?v=mmRb9MsgmXU&list=PLBAufArA9ptTg9wX_wrdUGFE2E73e4A4S&index=2
can someone please confirm ?
I also couldn't find any testimonial of any on-premise deployment, without the need for Github Entreprise. Is this possible ?

Thanks

**Comment by gordonwoodhull** [comment]
Hi @aschmu, thanks for your question. Due to licensing issues we replaced GitHub Enterprise on our private instances of RCloud.

We use a replacement service called [rcloud-gist-services](https://github.com/att/rcloud-gist-services) which was developed by some of the same folks who develop RCloud.

We don't make a big deal about it because we don't claim that it can replace Gists in all cases, but it serves us well for RCloud. It enables a couple of extra features like shared accounts, where a special user ID can have its notebooks edited by multiple people. It also simplifies authentication.

There's some documentation here:

https://github.com/att/rcloud/wiki/GitHub-to-Gist-Service-Migration

The info on rcloud.social probably needs to be updated.

I'll close this, but feel free to continue commenting if you have any questions!
