### ISSUE TITLE
Don't show stack trace by default on errors, hide in in expandable area

### ISSUE THREAD

**Issue by s-u** [att/rcloud#2642]
Wish: put RCloud error stack traces in a foldable UI so that it is not shown initially only when expanded

Details:
Errors in RCloud are currently shown in a huge red window that contains the error as well as the stack trace. Since the stack traces are typically quite long, it is very confusing to the user as they may not even be able to locate the error in the mess.

We need some way to separate the error and the trace. One suggestion is to make the trace expandable or to show just the top part of it. Also make it look different so the actual error is distinguishable.

This is indirectly related to #2606 in that the errors are confusing, but this piece is about the visual issue of the actual cause being buried in a huge visual mess regardless of the wording.

**Comment by gordonwoodhull** [comment]
Much earlier we also had #548 collapsing error traces.

I would suggest:
- collapse the error and only show the first line (or whatever the actual message is: needs testing)
- allow advanced users to click an icon (or the message?) to expand 
- include a copy button which copies the entire stack trace, since we usually need all of it to troubleshoot reports sent by users

**Comment by gordonwoodhull** [comment]
We decided, instead of a copy button, just to have an "email bug report" link - less chance for misunderstanding that way. It requires a new configuration setting like `support.email` or some such. It will copy the entire stack trace into a new email message using a `mailto:` link.
