### ISSUE TITLE
customization of "authentication failed" page

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2699]
With more details, HTML customization, various paths like bad token, no token, etc.

**Comment by s-u** [comment]
The following point should be configurable:

`login.R` is requested to make authentication (typically on behalf of the user entering login/pwd) by `execLogin=action` using `session.server.auth()`. If this fails a configuration `authfail.page` is consulted and re-directed to that page, otherwise "Authentication failed - please check your username and password." is shown (the latter is the current behavior).

(For completeness, if `login.R` encounter missing user of token cookies, or if the current cookie token is invalid, it will re-direct to the welcome page which is expected to request credentials.)

`login_successful.R` expects valid user/token cookies and if they are not valid, consult `tokenfail.page` configuration for a redirect or output "Invalid token, could not authenticate with the back-end" (as currently).
