### ISSUE TITLE
MathJax URL in scripts/fetch-mathjax.sh seems to be broken

### ISSUE THREAD

**Issue by s-u** [att/rcloud#2711]
The MathJax URL used in [scripts/fetch-mathjax.sh](https://github.com/att/rcloud/blob/develop/scripts/fetch-mathjax.sh) doesn't seem to yield working MathJax anymore. I had more luck with `https://github.com/mathjax/MathJax/archive/2.7.7.tar.gz` - but I wonder if it was just me or the repo truly changed.

**Comment by gordonwoodhull** [comment]
Confirmed and fixed, along with printing a warning rather than failing when `MathJax` is not present. (I think JS implementations got more strict about undefined variables since we started RCloud.)

It looks like it was a mistake to fetch a "branch" tarball (`legacy`) rather than a specific version, because it could change under us.
