### ISSUE TITLE
We need a way to run R code that does not add a cell to the notebook

### ISSUE THREAD

**Issue by cscheid** [att/rcloud#622]
People tend to not remove cells with errors, so they litter the notebook. A prompt that doesn't record notebook cells would mitigate that.

**Comment by gordonwoodhull** [comment]
I disagree with this and #665 both.  Run everything in the notebook because then we are sure it is all saved and no code ever gets lost.

**Comment by martymcwizard** [comment]
I agree with Gordon.  "Leave no code behind" Keep a record of everything, the user can figure out how to go back and edit and move the commands in what is effectively a history file, in a way that is much easier to do than editing a history file.  personally I think if the 'cell' structure can optionally be faded into the background to the point that the user doesn't necessarily realize that they have cells, they think they have a R session, then we can move them past the 'visual hurdle' of using the notebook model.  More thoughts in a future issue...

**Comment by gordonwoodhull** [comment]
This is another face of #665, which I currently think is out of scope until we have a really brilliant idea (or incredible amounts of resources to try everything and see what works out).

**Comment by gordonwoodhull** [comment]
I am closing this and #665 because I think that having multiple selection of cells and delete/crop/cull are the correct ways to manage this, rather than supporting some sort of throwaway or straight command-line mode. If there is a problem with proliferation of cells, make it easier to clean up cells. Even better if we could do this automatically, but it doesn't mean we shouldn't create cells in the first place.
