### ISSUE TITLE
Crop / cull cells

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#658]
Often when trying stuff out you end up with a bunch of junk cells.

There should be a command to select which cells you want to keep, and delete the rest.  Since we support "sortable" dragging and dropping of cells, why not treat cells as items more thoroughly:

 - when you click on a cell title/gutter it becomes "selected" with a border
 - you can cmd/ctrl-click to add to the selection
 - shift-click to select a range
 - (there are confusing ctrl-shift-click standards we could consider for the obsessive users)
 - <delete> deletes those cells
 - look at what Crop is usually mapped to (as in #300, naming is hard and we should look for standards). Crop is the inverse of delete, deletes every cell except those selected.

In order for the key commands to work, we'll have to make sure that all ace editors get deactivated when these sorts of commands happen. This is entirely standard and reasonable, just something we've never done. I'll open another issue on that.

**Comment by gordonwoodhull** [comment]
no, this is not a duplicate.  #665 is about having parallel areas and being able to move code easily between notebook and session.  this is still about running everything in the notebook, but being able to more easily edit the cells en masse.

**Comment by shaneporter** [comment]
Rather than showing a border around the cell (which would contract the cell's contents), perhaps a semi-transparent background to indicate selection would be more attractive, and obvious, to the user?

![image](https://cloud.githubusercontent.com/assets/2493614/12643728/c206e5da-c5b5-11e5-9647-2ce952608e0a.png)

I'm also thinking that when the user selects 2 or more cells, it would be useful to show a panel that lists the selected cells by name. If the panel had a button, such as 'inverse selection', it would be easier to understand than 'crop', prior to a delete. Most obviously, a `DEL` key shortcut would do the job of deleting, but a 'Delete' button on the panel could do the same.

In the future, the panel could be developed further, so that users could print cells selectively.

**Comment by gordonwoodhull** [comment]
I agree with the transparent background - I guess it is technically an overlay with `pointer-events: none`?

I'm not sure about the panel - it's always an issue of screen real estate. Even with the navbar buttons, which sound like a good idea, space is tight especially on laptops. In particular, I don't think we need a print button - for now, we can have print always print the selection if there is any, and we can consider custom print options or print preview with options later. 

Another problem with the panel is that usually the cell numbers aren't very useful for identifying them, especially since the cell numbers are not sequential (see #1219). Users will anyway have to scroll around to remember what cells 2 and 4 are, so the panel might be helpful as a summary but won't really tell the whole story in itself. Even if the panel were a thumbnail of the whole notebook, that wouldn't help if all the cells are text without graphical results.

As for invert vs crop, these are also good ideas and I think we should have both. Invert will be easier for most people to understand but power users can go straight to crop. I like having multiple ways of doing things.

So I guess we can start with delete and invert selection navbar buttons, crop as just a key command. 

(Conceivably crop could also be available with e.g. alt-clicking the delete button but then that would imply that therefore alt-delete is the crop key, which I'm not sure is standard or advisable. Also, does the navbar button change its icon every time you press alt, and blah blah blah. All stuff we can think about after we get the feature out on the dev servers and get some feedback on it.)

**Comment by gordonwoodhull** [comment]
I guess we also need a way to clear the selection - since one of the usual modifiers is toggle, that's one way out but not very intuitive. I guess clicking on the welcome banner or the blank space below the notebook is pretty obvious.

**Comment by shaneporter** [comment]
I've almost implemented this functionality, but have the following comments:

- **Problem**: Adding a selection with CTRL/CMD + Click doesn't feel natural. **Proposed Solution**: Toggle selections with a click (checkbox-style behaviour, gmail);
- **Problem**: Clicking in the gutter feels clumsy when the cell is being edited, since this action is currently assigned to line selection, and clicking in the header for the cell is already assigned to drag and move. **Proposed Solution**: Add a checkbox in the gutter, which is a clearer UI paradigm for selection (gmail, for example);
- **Problem**: Clicking the welcome banner or blank space below the notebook to clear a selection is not particularly intuitive. Toggling (or cropping) the selection is not easily handled with existing UI. **Proposed Solution**: Add a small horizontal bar with a checkbox drop down menu aligned horizontally to the cells' selection checkbox. Add menu items for 'select all', 'clear selection', 'toggle', 'crop', and 'delete' (delete can also be performed by tapping `del`.)

A screenshot of gmail to illustrate the checkbox/checkbox menu idea:

![image](https://cloud.githubusercontent.com/assets/2493614/12764472/e934855a-c9f1-11e5-8ede-8b41faf1ffce.png)

**Comment by gordonwoodhull** [comment]
I hear you about it being perhaps less intuitive, however the problem I'm trying to mitigate is that checkboxes are a very small target to click on. 

Already deleting cells by clicking the trashcan is pretty difficult so I was hoping to have great big areas to click on in the same way as dragging and dropping cells.

This should be a very quick action and not require the second or so it takes to zero in on a tiny control on each cell.

Perhaps a compromise would be to allow both interfaces: when you click on a cell title it selects just that cell and ticks the checkmark. When you control-click another cell title, both are ticked. 

Or you can directly click the checkboxes if you like.

With both interfaces, I think it is also worth enabling the sequential shift-click stuff that you think no one uses in the file explorer. People really use that stuff. In Gmail you can see how shift-click adds a range from the last thing clicked to the thing currently clicked.

It looks like we have not supported dragging the gutter for some time, so that's a red herring.

I like the bar with a global checkbox but i'm having trouble justifying using all that screen real estate for it, since it will have to show at all times and right now we will only have a single checkbox in it. Gmail is able to merge this "selection bar" with the rest of the navbar and it would be wonderful if we could do the same thing, but I don't see how, given how our layout currently works.

**Comment by shaneporter** [comment]
I didn't comment negatively towards CTRL/SHIFT-Click; I think we _should_ do it since it's really useful.

My criticism was towards CTRL/CMD-Click, especially when used with checkboxes - I just don't think it's needed.

I agree that the 'trashcan' icon is pretty difficult to interact with, but by extension, every other icon in that area is too. It feels quite cluttered.

I feel that the multi cell select functionality to support a multiple 'delete' operation will improve the user experience, but why don't we extend it even further?

Create a toolbar at the top of the central column and add a 'selection' drop down (for select all, select none, inverse) and move the cell icons to that toolbar. Not all the icons' actions work well with multiple selections, but if we give the user the ability to do a select and delete, then other actions, such as 'show/hide results' and 'run' could apply too. Other options would only apply to a single cell selection. 

We'd have a select and action workflow, and a much less cluttered cell area.

**Comment by gordonwoodhull** [comment]
Right, ctrl-click would only be needed for selecting cells using their titles. I am okay with worrying about that later, as a shortcut, with checkboxes being the primary interface. And I think we should try the selection bar.

Select and delete clearly belong in this selection bar. However, I think you'll find on consideration that the other commands don't really make sense there and will slow down the interface. At a minimum, the language indicator/selector is definitely per-cell. And wouldn't selecting a cell with a checkbox in order to show or hide the results using a button up top be kind of cumbersome? The edit button would make no sense there either.

I'm sympathetic to cleaning up the interface, but let's try to do it incrementally, since there are a lot of other projects to work on and I don't want to get bogged down in a huge redesign all at once.

So how about just a selection bar, and move delete there, for now?

**Comment by shaneporter** [comment]
Yeah, I agree that there will be a slow-down with some actions following a migration of buttons. So, no worries at all with your response.

Just so we're singing from the same hymn sheet, I'll implement the following (and please shout if you have comments):

- Remove delete icon from the icons on the right of a cell (the 'trashcan').
- Cells are selected with by CTRL/CMD clicking their header. (Shift-click will select a range). Checkboxes will not be used for selection.
- A selection bar will be introduced, with a drop down for commands to select all, none, invert, crop etc.
- A 'trashcan' button will be added to the selection bar that will delete selected cells.
- A keyboard shortcut for delete, `DEL`, will be added to init.js.

Thanks.

**Comment by gordonwoodhull** [comment]
That looks good. 

I'm a fan of redundant ways to do things, so if we are using checkboxes to indicate selection (in addition to highlighting like gmail does?), then clicking on the checkboxes should also work.

**Comment by gordonwoodhull** [comment]
Implemented in #1809
