### ISSUE TITLE
long titles can cause navbar layout problems

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#972]
Jyothi reports:

> rcloud has some UI issues.  I have refreshed the page a few times but still have problems with the UI.  Below is the screen shot - navigating the Notebooks panel and the code panels is tricky.

![navbar-munch](https://cloud.githubusercontent.com/assets/1366709/4743224/c9fc64d8-5a25-11e4-8e1b-df45a332969e.png)

**Comment by gordonwoodhull** [comment]
Patch was delivered, but is incorrect / needs rewriting.  Deferring this issue.

**Comment by holyguster** [comment]
Just bumping this issue.  It might have become more common now that the "Forum" and "About" links are now back in the top ribbon.

Two screen shots attached:

 - One where you can see everything that should be visible, and
 - a second after I made the browser more narrow.  On the second one, these panes are no longer accessible because they are covered up by the top ribbon:  Notebooks, Search, Assets, and File Upload.  Actually, Search and File Upload are still clickable (as part of those pane titles are visible), but I can't see the words "Search" or "File Upload" any longer.

Also, I can't see the other stuff that would be at the top of the center pane, like the RCloud/R version info or the "Find" UI (activated with Cmd-F or Ctrl-F).

![no_wrap](https://cloud.githubusercontent.com/assets/927657/9047160/f2b0dacc-39fd-11e5-8149-a4811930a510.PNG)
![with_wrap](https://cloud.githubusercontent.com/assets/927657/9047161/f4fbd336-39fd-11e5-8985-a2dca4d0a2f6.PNG)

**Comment by gordonwoodhull** [comment]
Phew. FINALLY.
![title resize](https://cloud.githubusercontent.com/assets/1366709/9213778/2aaa1864-4064-11e5-89a4-215f3e2ff0b7.gif)

**Comment by gordonwoodhull** [comment]
meanwhile, the forked from title simply isn't laid out, so it just clips when the window is small

**Comment by holyguster** [comment]
Nice!!!

**Comment by gordonwoodhull** [comment]
active on rcloud-2 if you wanna try to break it... it would still be good if when it still gives up and piles up, for the rest of the stuff to move down rather than getting covered up. 

so in the worst case, this is still not solved, just down to about 970px with all the, er, features, we've got on Research

**Comment by gordonwoodhull** [comment]
it would also be nice to use that last little bit of space - i don't know where the big gap between title and menu comes from.
